# __Numpy__
Array 연산에 최적화.  
배열(Array)이란 순서가 있는 같은 종류의 데이터가 저장된 집합.

In [1]:
import numpy as np
def p(*t): print(*t); return

In [2]:
# numpy array는 list를 받는다.
a1 = np.array([0,1,2,3,4,5])
p( a1 )
a2 = np.array([0,1,2,3,4,0.05])
p( a2 )     # 데이터의 종류를 맞추기 위해 float으로 바뀜.
p( a1.dtype, a2.dtype )

[0 1 2 3 4 5]
[0.   1.   2.   3.   4.   0.05]
int32 float64


In [3]:
# 다차원 배열 생성 가능.
p( np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]]) )

# 파이썬 range와 비슷하게 arange로 범위 지정 가능.
p( np.arange(5) )
p( np.arange(3, 13, 2) )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2 3 4]
[ 3  5  7  9 11]


### __reshape__     __shape__

In [4]:
t = np.arange(12)
p( t )                   # reshape는 데이터의 크기가 맞아야 한다. 3 x 4 = 12
p( t.reshape(3, 4) )     # reshape는 결과를 return함. 근데 저장안해서 초기화됨.
p( t.shape )             # 그리고 1차원 배열은 (12,) 이런식으로 출력됨.

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(12,)


### __linspace__
범위의 시작과 끝 그리고 개수를 넣으면 알아서 분할. 끝점을 포함할지도 선택 가능.                   <br>
linspace(start, end, numOfSlices=50, endpoint=True, retstep=False)

In [5]:
t = np.linspace( 1, 10, 10)
p( t.dtype )             # 정수로 나눠 떨어져도 float임.
t     

float64


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
t = np.linspace( 1, 10, 10, False, retstep=True)    # endpoint를 False해서 마지막 10 제외함.
t                                                   # retstep=True 라서 스텝을 같이 리턴함.   return step의 준말.

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

### __zeros__  __ones__  __eye__ 
zeros(shape = int | tuple, dtype=float64, order='C', *, like=None)                                                                                                 <br>
eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)                                                                                            <br>
기본 자료형은 다 **float**이다.                                                                                                                                                                         <br>
eye는 단위행렬이므로 보통 매개변수 하나만 쓰고 대칭 행렬(Symmetric Matrix)로 출력됨.  

In [7]:
p( np.zeros(3) )
p( np.zeros((2,4)) )
p( np.ones(5) )
p( np.ones((3,2), "int32") )
template = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.zeros_like(template)                   # like 매개변수는 zeros_like ones_like 로 쓰는게 더 편하다.
p( arr )

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]
 [1 1]]
[[0 0 0]
 [0 0 0]]


In [8]:
p( np.eye(3))
p( np.eye(3,5, dtype="int32") )       # eye가 단위행렬이라고 대칭행렬만 가능한건 아니다. 3x5로 만들면 초과된 2열은 0으로 채워 만들 수 있다.
np.eye(3,5, k=2, dtype="int32")       # k에 값을 주면 주대각 위치가 바뀜. k=2를 줬기 때문에 위로 2이동.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### __데이터 타입의 종류들__
b　　　bool                                                                                                                                  <br>
i　　　signed integer                                                                                                                                  <br>
u　　　unsigned inteager                                                                                                                                  <br>
f　　　floating-point                                                                                                                                  <br>
c　　　복소수. complex-floating point                                                                                                                                  <br>
M　　　datetime                                                                                                                                  <br>
O　　　(Python) objects                                                                                                                                  <br>
S | a　　바이트 문자열. (byte) string                                                                                                                                  <br>
U　　　Unicode                                                                                                                                 <br>
> 데이터 타입 변환                                                                                                                                 <br>
리턴_받을_변수 = 변환할_배열.astype(dtype)

In [9]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [10]:
temp = np.array(['1.567', '0.123', '5.123', '9', '8'])
p( temp.dtype )
result = temp.astype(float)
result

<U5


array([1.567, 0.123, 5.123, 9.   , 8.   ])

### __난수 배열__
np.random.rand(d0, d1, ..., dn)　　　　　　여기서 d0, d1은 dimension (차원) 이다.  
np.random.randint(low, high=None, size=None, dtype=int)

In [11]:
p( np.random.rand() )        # 차원을 입력하지 않으면 0차원 점마냥 랜덤 수 하나를 리턴.
np.random.rand(2,3)              # rand는 0이상 1미만의 실수를 리턴한다.

0.19666539326637222


array([[0.30971021, 0.6574833 , 0.04846202],
       [0.71074833, 0.08041549, 0.00628473]])

In [12]:
p( np.random.randint(10) )           # 0이상 10미만의 정수를 0차원으로 리턴.
np.random.randint(10, size=(3, 4))           # 0이상 10미만의 정수를 3*4배열로 리턴.

7


array([[9, 1, 3, 5],
       [3, 5, 6, 4],
       [5, 5, 6, 1]])

### __배열 연산하기__ - 기본

In [13]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
p( arr1, arr2, "\n")
p( arr1 + arr2 )
p( arr1 - arr2 )
p( arr1 * arr2 )
p( arr1 / arr2 )
p( arr1 * 3 )
p( arr1 ** arr2 )
p( arr1 / arr2**2 )
p( arr1 > 20)               # 비교도 가능

[10 20 30 40] [1 2 3 4] 

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 30  60  90 120]
[     10     400   27000 2560000]
[10.          5.          3.33333333  2.5       ]
[False False  True  True]


In [14]:
t = np.arange(1,6)
print( t )
print( t.sum() )
print( t.mean() )      # 평균
print( t.std() )       # 표준편차
print( t.var() )       # 분산. 표준편차의 제곱
print( t.min() )
print( t.max() )
print( t.cumsum() )     # Cumulative Sum (누적 합)  axis=None 으로 누적합을 계산할 축을 정할 수 있다.
print( t.cumprod() )    # Cumulative Product (누적 곱)  axis=None 으로 누적합을 계산할 축을 정할 수 있다.

[1 2 3 4 5]
15
3.0
1.4142135623730951
2.0
1
5
[ 1  3  6 10 15]
[  1   2   6  24 120]


### __배열 연산하기__ - 행렬 연산
|행렬 연산 |사용법|
|---------------------------|------------------------------|
|행렬곱 matrix product|A.dot(B)　np.dot(A,B) |
|전치행렬 transpose matrix|A.transpose()　np.transpose(A) |
|역행렬 inverse matrix|np.linalg.inv(A) |
|행렬식 determinant|np.linalg.det(A) |

In [15]:
A = np.array([0, 1, 2, 3]).reshape(2,2)
B = np.array([3, 2, 0, 1]).reshape(2,2)
print(A); print(B)
A.dot(B)
np.dot(A,B)

[[0 1]
 [2 3]]
[[3 2]
 [0 1]]


array([[0, 1],
       [6, 7]])

In [16]:
A.transpose()
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [17]:
p( np.linalg.inv(A) )
np.linalg.det(A)

[[-1.5  0.5]
 [ 1.   0. ]]


-2.0

### __Indexing, Slicing__

In [18]:
arr = np.array([0, 10, 20, 30, 40, 50])
p( arr[1] )
p( arr[1:4] )
p( arr[:3])
p( arr[[1,5,4,3]])       # index를 특정해서 뽑고 싶을 땐, []리스트안에 한 번 더 넣어야 한다.

10
[10 20 30]
[ 0 10 20]
[10 50 40 30]


In [19]:
arr = np.arange(10, 100, 10).reshape(3,3)
p( arr ,"\n")

p( arr[1] )
p( arr[0,2] )       # 주의 ★
arr[2,2] = 99
p( arr )
arr[1] = np.array([47, 57, 67])
p( arr )

[[10 20 30]
 [40 50 60]
 [70 80 90]] 

[40 50 60]
30
[[10 20 30]
 [40 50 60]
 [70 80 99]]
[[10 20 30]
 [47 57 67]
 [70 80 99]]


In [20]:
arr[[0, 2, 2], [0, 1, 2]]    # 2차원에서 여러 원소 선택하기.★  앞부분에 행들을 모아놓고, 뒷부분에 열들을 모아놓는 구조라서 보기 어렵다.

array([10, 80, 99])

In [21]:
p( arr[arr>50] )        # 조건문을 넣어서 조건에 맞는 요소만 뽑을 수도 있다. ★
arr[(arr%2)==0]

[57 67 70 80 99]


array([10, 20, 30, 70, 80])

In [22]:
arr = np.array([0, 10, 20, 30, 40, 50])
p( arr )
arr[2:5] = np.array([25, 35, 45])        # 슬라이싱하고 삽입도 가능. 이 때 슬라이싱된 요소 수랑 삽입되는 요소 수랑 같아야 함.
p( arr )
arr[3:6] = 60                            # 슬라이싱 후 배열이 아닌 단일로 입력하면, 해당 값으로 초기화되는 효과.
p( arr )

[ 0 10 20 30 40 50]
[ 0 10 25 35 45 50]
[ 0 10 25 60 60 60]


2차원 배열 슬라이싱
<blockquote> arr[행시작:행끝, 열시작:열끝] </blockquote>
특정 행을 선택한 후 열을 슬라이싱
<blockquote>arr[행, 열시작:열끝]</blockquote>

In [23]:
arr = np.arange(10, 100, 10).reshape(3,3)
p( arr )
p( arr[1:3,1:3] )
p( arr[:3, 1:] )
p( arr[1][0:2] )
p( arr[1:3, 0] )
arr[0:2, 1:3] = np.array([[34, 56], [78, 99]])
p( arr )

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[50 60]
 [80 90]]
[[20 30]
 [50 60]
 [80 90]]
[40 50]
[40 70]
[[10 34 56]
 [40 78 99]
 [70 80 90]]


In [24]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3])
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 