In [2]:
import numpy as np; import pandas as pd; p = print; import matplotlib.pyplot as plt; from sklearn.datasets import load_iris; from seaborn import load_dataset

# Python ~ Numpy ~ Pandas

**▶ range / reversed**

In [3]:
'''
range도 기본적으로 sequence형이라 iterable하게 쓸 수 있는 것이다.
    - 인덱싱과 슬라이싱 가능
'''
print(range(1, 11)[7])
print(range(1, 11)[3:7])    # range를 슬라이싱하면 range 객체로 나온다.
'''
reversed는 reversed 객체로 리턴됨.
'''
print(reversed('abcde'))
print(reversed([1, 2, 3 ,4, 5]))
print(reversed((1, 2, 3, 4, 5)))
print(reversed(range(10)))

8
range(4, 8)


**▶ ndarray**

In [28]:
'''
numpy 배열을 만들 때 dtype 인자를 사용하면 데이터 타입을 바꿀 수 있다.  ★
'''
print(arr:=np.array([3, 4, 5, 6], dtype='str'))
print(type(arr))
print(np.zeros((2, 4), dtype='float'))
print(np.full((2, 5), 9))       # 9로 채운 행렬 만들기
print(np.identity(3))           # 단위행렬
p()
arr = np.arange(1, 13).reshape(4, -1)
print(arr)
print(arr[-2, -2])
print(arr[-3:, 1:])
print(arr[1:3, :])

['3' '4' '5' '6']
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[9 9 9 9 9]
 [9 9 9 9 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
8
[[ 5  6]
 [ 8  9]
 [11 12]]
[[4 5 6]
 [7 8 9]]


In [40]:
# abs(numpy.ndarray)
arr = np.array([3, -4, -5, 6, 0])
print(np.abs(arr))
print(np.fabs(arr))     # 복소수가 아닌 경우에는 fabs로 빠르게 연산 가능하다고 함
print(np.sign(arr))     # 부호만 가져옴. 0의 부호는 0
'''넘파이 연산
     np.sqrt(arr)  np.square(arr)  np.exp(arr)  np.log(arr)  np.log10(arr)
     np.round(arr, 2)  np.ceil(arr)  np.floor(arr)'''
print(np.trunc([3.14, -4.15, -5.79, 6.88]))     # 일반적인 올림, 내림과는 다르게 소수점 파트를 삭제함.
'''형상 변환 
     arr.reshape()  arr.ravel() == arr.flatten()  arr.transpose()
   통계
     np.mean(arr)  np.min(arr)  np.max(arr)
     np.var(arr, ddof=None)  np.std(arr, ddof=None)     ← ddof = 자유도. 표본 통계량을 구할 때는 ddof=1을 줘야 함. ★
     np.argmin(arr)  np.argmax(arr)                    ★
'''; p()

[3 4 5 6 0]
[3. 4. 5. 6. 0.]
[ 1 -1 -1  1  0]
[ 3. -4. -5.  6.]



**▶ DataFrame**

In [53]:
'''
    pd.DataFrame(object, index, columns)
'''
df = pd.DataFrame({
    'Name': ['Olivia', 'Lucas', 'Sophia', 'Zoe', 'Aca', 'Elliot'],
    'Sex': ['F', 'M', 'F', 'F', 'F', 'M'],
    'Age': [22, 32, 27, 24, 38, 19]
}, index=list('abcdef'))
display(df)
print(df.iloc[3, 0])
print(df.loc['d', 'Age'])
print(df.iloc[2:5])
print(df.loc['c':'e'])      # loc는 마지막 슬라이싱 행이 포함됨. 지져스
print(df['Name']['c'], df['Name'][2])       # 인덱서 없이 인덱싱할 때는 열 → 행 순서. 걍 loc나 iloc 쓰자.

Name Sex  Age
a  Olivia   F   22
b   Lucas   M   32
c  Sophia   F   27
d     Zoe   F   24
e     Aca   F   38
f  Elliot   M   19

Zoe
24
     Name Sex  Age
c  Sophia   F   27
d     Zoe   F   24
e     Aca   F   38
     Name Sex  Age
c  Sophia   F   27
d     Zoe   F   24
e     Aca   F   38
Sophia Sophia


In [68]:
'''데이터 프레임의 통계
        df.describe()  df.count()  df.mean()  df.min()  df.max()
        df.var(ddof=1)  df.std(ddof=1)      ← 넘파이와는 다르게 ddof=1이 디폴트 ★
        df.median()  df.quantile(q=0.5)  df.mode()     ★

   입출력
        pd.read_csv(path, sep=',', encoding=None)
        pd.to_csv(path, index=True)

   정렬
        df.sort_values(by, ascending=True, axis=0)
        df.sort_index(axis=0, ascending=True, level=None)       ← axis=1이면 열 인덱스(특성 순서)을 정렬함

   순위
        df.rank(axis=0, method='average', ascending=True)

   컬럼 추가, 삭제, 구간화
        df['컬럼명'] = 추가할 컬럼
        df.insert(loc, column, value)
        df.drop(labels, axis=0)
        pd.cut(x, bins, labels=None, right=True)        ← 구간화(비닝, binning)
        pd.qcut(x, q, labels=None, right=True)          ← 분위수 기반의 구간화
'''
iris = pd.DataFrame(load_iris()['data'], columns=load_iris()['feature_names'])
iris['cut'] = pd.cut(iris['sepal length (cm)'], bins=5)
print(iris['cut'].unique())

[(5.02, 5.74], (4.296, 5.02], (5.74, 6.46], (6.46, 7.18], (7.18, 7.9]]
Categories (5, interval[float64, right]): [(4.296, 5.02] < (5.02, 5.74] < (5.74, 6.46] < (6.46, 7.18] < (7.18, 7.9]]


# 데이터 인코딩

**▶ Label Encoding**

In [10]:
'''
- 단순하게 문자열 값을 숫자형 카테고리 값으로 일대일로 변환.
- 숫자가 대소의 의미를 가지게 되므로, 가급적 트리 계열과 같은 특정 머신러닝 알고리즘에서만 사용해야 한다.
- 넘파이의 select()나 판다스의 map()으로도 같은 기능 가능
'''
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({'Class': ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F']})
display(df)

encoder = LabelEncoder()
df_encoded = encoder.fit_transform(df)  # 경고메시지는 1d array로 입력하라는 것. df['class']
display(df_encoded)
print(encoder.classes_)
print(encoder.inverse_transform(df_encoded))    # 디코딩

Class
0     A
1     B
2     A
3     C
4     E
5     D
6     D
7     A
8     F

c:\Users\ALT\anaconda3\envs\bbg\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([0, 1, 0, 2, 4, 3, 3, 0, 5])

['A' 'B' 'C' 'D' 'E' 'F']
['A' 'B' 'A' 'C' 'E' 'D' 'D' 'A' 'F']


**▶ One-Hot Encoding**

In [28]:
'''
- get_dummies() 후에 concat((), axis=1) 을 사용
- OneHotEncoder는 LabelEncoder나 .values등으로 1차원 넘파이로 변환 후 2차원으로 다시 변환해야 함.
- 넘파이의 where() 나 판다스의 loc인덱서 + 부올린 인덱싱으로도 가능.
'''
df = pd.DataFrame({'Class': ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F']})
display(df)

df_encoded = pd.get_dummies(df)
pd.concat((df, df_encoded), axis=1)

Class
0     A
1     B
2     A
3     C
4     E
5     D
6     D
7     A
8     F

Class  Class_A  Class_B  Class_C  Class_D  Class_E  Class_F
0     A        1        0        0        0        0        0
1     B        0        1        0        0        0        0
2     A        1        0        0        0        0        0
3     C        0        0        1        0        0        0
4     E        0        0        0        0        1        0
5     D        0        0        0        1        0        0
6     D        0        0        0        1        0        0
7     A        1        0        0        0        0        0
8     F        0        0        0        0        0        1

In [35]:
titanic = load_dataset('titanic')
display(titanic.head(3))

titanic['요금_대중소'] = pd.cut(titanic['fare'], bins=[0, 20, 70, 300], labels=['low', 'middle', 'high'])
titanic_encoded = pd.get_dummies(titanic['요금_대중소'])
display(pd.concat((titanic, titanic_encoded), axis=1))

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  요금_대중소  low  middle  \
0      man        True  NaN  Southampton    no  False     low    1       0   
1    woman       False    C    Cherbourg   yes  False    high    0       0   
2    woman       False  NaN  Southampton   yes   True     low    1       0   
3    woman       False    C  Southampton   yes  False  middle    0       1   
4      man        True  NaN  Southampton    no   True     low    1       0   
..     ...         ...  ...          ...   ...    ...     ...  ...     ...   
886    man        True  NaN  Southampton    no   True     low    1       0   
887  woman       False    B  Southampton   yes   True  middle    0       1   
888  woman       False  NaN  Southampton    no  False  middle    0       1   
889    man        True    C    Cherbourg   yes   True  middle    0       1   
890    man        True  NaN   Queenstown    no   True     low    1       0   

     high  
0       0  
1       1  
2       0  
3       0  
4       0  
..    ...  
886     0  
887     0  
888     0  
889     0  
890     0  

[891 rows x 19 columns]

### 데이터 스케일링

**▶ StandardScaler**  
- 평균을 기준으로 얼마나 떨어져 있는지를 나타냄
- 표준화 후, 특정 범위를 벗어난 데이터를 이상치로 판별할 수도 있음

**▶ MinMaxScaler**
- 데이터군내에서 특정 개체가 가지는 위치를 파악하고 비교할 때 사용

### 데이터 축소

**▶ PCA　(Principal Component Analysis, 주성분분석)**  

In [50]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

df = pd.read_csv('samples/예제/USArrests_rownames.csv', index_col=0)
display(df.head(3))

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)

pca = PCA(4)    # n_components=4 주성분 개수를 전체 컬럼 수로.
pca_arr = pca.fit_transform(df_scaled)
print('분산 기여율: ', pca.explained_variance_ratio_)
print('누적 기여율: ', pca.explained_variance_ratio_.cumsum())      # 주성분 개수를 2개로 정함

pca = PCA(2)
pca_arr = pca.fit_transform(df_scaled)
pd.DataFrame(pca_arr, columns=['PCA1', 'PCA2']).head()

Murder  Assault  UrbanPop  Rape
Alabama    13.2      236        58  21.2
Alaska     10.0      263        48  44.5
Arizona     8.1      294        80  31.0

분산 기여율:  [0.62006039 0.24744129 0.0891408  0.04335752]
누적 기여율:  [0.62006039 0.86750168 0.95664248 1.        ]


PCA1      PCA2
0  0.985566  1.133392
1  1.950138  1.073213
2  1.763164 -0.745957
3 -0.141420  1.119797
4  2.523980 -1.542934

### 데이터 결합 및 요약

**▶ concat**
- 물리적으로 연결

**▶ merge**
- df1.merge(df2, how='inner', on=컬럼명)
- 고유한 키를 기준으로 두 데이터프레임을 병합 = 조인 (how='inner'가 디폴트. 'left', 'right', 'outer'도 가능)

**▶ groupby**

**▶ agg**

**▶ map**
- 시리즈에만 사용 가능

**▶ apply**


### 결측치와 이상치



### 텍스트 데이터와 날짜시간 데이터

# 가설 검정  
모집단에 대한 가설을 설정한 후 그 가설의 타당성 여부를 검정하는 것.
- 상관분석
- 정규성 검정
- 모평균과 모분산 검정
- 카이제곱 검정
- 비모수 검정

### **▼ 상관분석**
- 데이터가 정규분포를 따를 때, 상관분석 -> 피어슨 상관계수

In [60]:
from sklearn.datasets import load_diabetes
from scipy import stats

diabetes = pd.DataFrame(load_diabetes()['data'], columns=load_diabetes()['feature_names'])
display(diabetes.head(2))

p, pvalue = stats.pearsonr(diabetes['age'], diabetes['bmi'])        # 피어슨 상관계수
print('피어슨 상관계수: ', p)
print('pvalue(유의확률): ', pvalue, pvalue < 0.05)
# 상관계수가 0.185로 두 컬럼은 서로 상관관계가 적은 것으로 나타났다. 하지만 귀무가설이 기각됐기 때문에, 상관계수는 작지만 유의하다는 것을 알수 있다.

display(diabetes[['age', 'bmi']].corr())        # 단순한 상관계수는 corr()로도 확인 가능.

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204

피어슨 상관계수:  0.18508466614655558
pvalue(유의확률):  9.076791865412659e-05 True


age       bmi
age  1.000000  0.185085
bmi  0.185085  1.000000

### **▼ 정규성 검정**
- 샤피로-윌크 검정　　(R언어의 한계 때문에 이거만. scipy.stats에는 더 다양한 정규성 검정 함수가 있음. kstest, anderson, jarque_bera 등)

In [63]:
from scipy import stats

np.random.seed(2024)
data = np.random.random(10)

s, pvalue = stats.shapiro(data)
print('통계량: ', s)
print('pvalue: ', pvalue, pvalue < 0.05)    # p-value가 매우 크므로 귀무가설을 기각할 수 없기 때문에, 정규성을 만족한다.

통계량:  0.8969665765762329
pvalue:  0.20285499095916748 False


### **▼ 모평균 검정**
- 표본 수에 따라 단일표본, 이표본 등으로 구분됨.
- 여기서는 단일표본 t-검정, 대응표본 t-검정, 독립표본 t-검정 이 세가지의 t-검정을 할거다.
    - 단측 검정할 때는 alternative='less', 'greater' 를 사용.

In [67]:
# t_test_1samp(데이터, 귀무가설값, alternative='two-sided')
from scipy import stats

kg = np.array([75.5, 83.9, 75.7, 56.2, 73.4, 67.7, 79.0, 50.7, 58.4, 74.1, 65.1, 77.8, 48.1, 46.3])
print(kg.mean())    # 모집단의 평균이 70이라고 할 수 있는지 단일표본 t-검정을 수행. (정규성 만족 가정)
t, pvalue = stats.ttest_1samp(kg, 70)
print('t통계량: ', t)
print('pvalue: ', pvalue, pvalue < 0.05)        # 귀무가설 채택. 모집단의 평균은 70이라고 할 수 있다.

66.56428571428572
t통계량:  -1.0289933120202257
pvalue:  0.3222484823978743 False


In [69]:
from scipy import stats

female = np.array([50.7, 58.4, 74.1, 65.1, 77.8, 48.1, 46.3])
male = np.array([75.5, 83.9, 75.7, 56.2, 73.4, 67.7, 79.0])
print('평균 차이: ', female.mean() - male.mean())       # 두 데이터의 모평균은 다르다고 할 수 있는지 대응표본 t-검정을 수행. (정규성 만족 가정)

t, pvalue = stats.ttest_rel(female, male)
print('t통계량: ', t)
print('pvalue: ', pvalue, pvalue < 0.05)        # 귀무가설 채택. 모집단의 평균은 서로 다르다고 볼 수 없다.

평균 차이:  -12.985714285714295
t통계량:  -2.0784469330649724
pvalue:  0.08291274205610197 False


In [70]:
from scipy import stats

# 바로 위의 데이터로 두 데이터가 독립이라고 가정한 후, 두 데이터에 대한 모평균이 서로 다르다고 할 수 있는 지 독립표본 t-검증을 수행. (정규성, 등분산성 만족 가정)

t, pvalue = stats.ttest_ind(female, male)
print('t통계량: ', t)
print('pvalue: ', pvalue, pvalue < 0.05)        # 귀무가설 기각. 모집단의 평균은 서로 다르다고 볼 수 있다.

t통계량:  -2.218664157777296
pvalue:  0.04655012211056963 True


### **▼ 모분산 검정**
- 모분산 검정도 표본의 수에 따라 구분됨.
- 단일표본에 대한 모분산 검정, 이표본에 대한 분산비 검정, 이표본 이상에 대한 Bartlett 검정과 Levene 검정

In [78]:
# 단일 표본에 대한 모분산 검정을 바로 수행하는 함수가 없어서, chi2으로 cdf해서 유의확률을 구해야 한다.
from scipy import stats

score = np.array([80.5, 60.2, 70, 87, 45, 91, 85])
var0 = 1100      # 귀무가설에서 설정한 모분산
sample_var = np.var(score, ddof=1)          # 표본 분산
print('표본 분산: ', sample_var)

stat = (len(score)-1) * sample_var / var0   # 검정 통계량
print('검정통계량: ', stat)
print(stats.chi2.cdf(stat, len(score)-1))   # 카이분포를 통해 직접 유의확률 계산. 좌측 검정이므로 Pr[chi2(자유도) < 검정통계량]으로 계산
print('> 검정 결과 p-value가 0.0416이므로 유의수준 5%에서 귀무가설을 기각. 모분산은 1100보다 작다고 할 수 있다.')
print(1 - stats.chi2.cdf(stat, len(score)-1))   # 우측 검정일 경우, Pr[chi2(자유도) > 검정통계량]으로 계산
print(2 * stats.chi2.cdf(stat, len(score)-1))   # 양측 검정일 경우, 2 * 좌측검정의 유의확률 또는 2* 우측검정의 유의확률로 계산

표본 분산:  278.1033333333333
검정통계량:  1.5169272727272727
0.041637780038918736
> 검정 결과 p-value가 0.0416이므로 유의수준 5%에서 귀무가설을 기각. 모분산은 1100보다 작다고 할 수 있다.
0.9583622199610813
0.08327556007783747


In [80]:
# 분산비 검정은 일반적으로 이표본에 대한 등분산 검정을 의미. 이 또한 바로 수행하는 함수가 없어서, f분포로 cdf해서 유의확률을 구해야 한다.
# 대립가설: a 모분산 < b 모분산으로 가정. 정규성 만족 가정.
from scipy import stats

a = np.array([70, 80, 75, 65, 100, 98])
b = np.array([20, 100, 50, 94, 28, 80, 95, 30])

var_a = np.var(a, ddof=1)       # 표본 분산
var_b = np.var(b, ddof=1)

stat = var_a / var_b
print('검정통계량: ', stat)         # 검정통계량 = a의 분산 / b의 분산 (가설: a 모분산 < b 모분산)
print(stats.f.cdf(stat, len(a)-1, len(b)-1))        # F분포로 직접 유의확률 계산. 좌측검정을 함.
print('> 유의확률이 0.0415로 유의수준 5%에서 귀무가설을 기각. a 모분산은 b 모분산보다 작다고 할 수 있다.')
print(1 - stats.f.cdf(stat, len(a)-1, len(b)-1))    # 우측 검정
print(2 * stats.f.cdf(stat, len(a)-1, len(b)-1))    # 양측 검정

검정통계량:  0.18681014154026346
0.04153943037562959
> 유의확률이 0.0415로 유의수준 5%에서 귀무가설을 기각. a 모분산은 b 모분산보다 작다고 할 수 있다.
0.9584605696243704
0.08307886075125918


In [86]:
# Bartlett 검정
# 이표본 이상에 대한 등분산 검정 방법 중 하나로 정규성을 충족해야함.
from scipy import stats

a = np.array([70, 80, 75, 65, 100, 98])
b = np.array([20, 100, 50, 94, 28, 80])
c = np.array([90, 97, 95, 94, 99, 100])

print(stats.bartlett(a, b, c))  # 유의확률이 0.05보다 작으므로, 그룹 간의 분산에 유의미한 차이가 있다고 볼 수 있다.

BartlettResult(statistic=15.6702722148674, pvalue=0.00039558846873743075)


In [87]:
# Levene 검정
# 이표본 이상에 대한 등분산 검정 방법 중 하나로 정규성을 충족하지 않는 데이터에 사용.
from scipy import stats

print(stats.levene(a, b, c))    # 유의확률이 0.05보다 작으므로, 그룹 간의 분산에 유의미한 차이가 있다고 볼 수 있다.

LeveneResult(statistic=14.365736704446384, pvalue=0.00032713621045500125)


**▶ 분산 분석 ANOVA**
- 분산 분석(ANOVA)는 두 집단 이상의 모평균을 검정하는 방법.
- 여기서는 일원배치 분산분석과 이원배치 분산분석만 다룰거임.

In [93]:
# 일원배치 분산분석
# A~C 세 학교에서 각각 1000명씩 층화 추출한 데이터를 활용해서 세 학교 간의 기말고사 성적의 평균이 서로 차이가 있는 지 검정. (성별, 학년의 비율은 세 학교가 동일, 정규성, 등분산성 등 만족 가정)
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

df = pd.read_csv('samples/예제/school_score.csv')
print(df.shape)
display(df.head(2))

one_way = ols('Final ~ C(School)', data=df).fit()
display(anova_lm(one_way))
# C(School)의 PR(>F)값이 매우 작으므로, 유의수준 5%에서 귀무가설을 기각. 세 학교의 기말고사 성적의 평균은 차이가 있다고 할 수 있다.

(3000, 5)


id School Sex  Grade  Final
0   1      A   M      1   44.4
1   2      A   M      2   47.7

df         sum_sq        mean_sq            F  PR(>F)
C(School)     2.0  996939.237147  498469.618573  5722.221007     0.0
Residual   2997.0  261072.308290      87.111214          NaN     NaN

In [94]:
# 사후검정 - Tukey의 HSD 검정
# 바로 위에서 세 학교의 평균에 차이가 있음을 알았지만, 세 학교가 모두 다른지, A와 B만 다른지, A와 C가 다른지는 알 수가 없다.
# 이를알기 위해서는 사후검정을 해야 한다.

from statsmodels.stats.multicomp import pairwise_tukeyhsd

print(pairwise_tukeyhsd(df['Final'], df['School'], 0.05))   # endog=df['Final'], groups=df['School'], alpha=0.05
# A와 B, A와 C 사이에는 평균에 유의미한 차이가 있다고 할 수 있고, B와 C는 유의미한 차이가 없다고 할 수 있다.
# 신뢰구간에 0을 포함하는지 아니면 reject 결과로 알 수 있다.

Multiple Comparison of Means - Tukey HSD, FWER=0.05 
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     A      B  38.8464   -0.0 37.8677 39.8251   True
     A      C  38.4922   -0.0 37.5135 39.4709   True
     B      C  -0.3542 0.6728 -1.3329  0.6245  False
----------------------------------------------------


In [100]:
# 이원배치 분산분석
# 이원배치 분산분석은 일원배치 분산분석과 유하하지만, formula 입력 방식에 차이가 있다.
# 교호작용이 있는 경우: '반응변수 ~ C(그룹1) + C(그룹2) + C(그룹1):C(그룹2)'
# 교호작용이 없는 경우: '반응변수 ~ C(그룹1) + C(그룹2)'

from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

df = pd.read_csv('samples/예제/school_score.csv')

two_way = ols('Final ~ C(School) + C(Grade) + C(School):C(Grade)', df).fit()
display(anova_lm(two_way))
print('> 이원배치 분산분석에서는 상호작용항의 유의성을 먼저 고려한다. 0.742912로 p-value가 매우 크므로, 상호작용 효과가 통계적으로 유의하지 않은 것을 알 수있다.')
print('> 교호작용이 유의하지 않으므로, 이를 고려하지 않고 다시 분산분석을 수행한다. \n')
two_way = ols('Final ~ C(School) + C(Grade)', df).fit()
display(anova_lm(two_way))
print('> 학교의 p-value는 매우 작으므로, 학교간의 평균차이는 있다고 볼 수 있고, 학년의 p-value는 0.05를 넘으므로, 학년간의 차이는 유의미하지 않다고 볼 수 있다.')

df         sum_sq        mean_sq            F  \
C(School)              2.0  996939.237147  498469.618573  5721.620556   
C(Grade)               2.0     324.472829     162.236415     1.862210   
C(School):C(Grade)     4.0     170.851257      42.712814     0.490274   
Residual            2991.0  260576.984204      87.120356          NaN   

                      PR(>F)  
C(School)           0.000000  
C(Grade)            0.155509  
C(School):C(Grade)  0.742912  
Residual                 NaN

> 이원배치 분산분석에서는 상호작용항의 유의성을 먼저 고려한다. 0.742912로 p-value가 매우 크므로, 상호작용 효과가 통계적으로 유의하지 않은 것을 알 수있다.
> 교호작용이 유의하지 않으므로, 이를 고려하지 않고 다시 분산분석을 수행한다. 



df         sum_sq        mean_sq            F    PR(>F)
C(School)     2.0  996939.237147  498469.618573  5725.518315  0.000000
C(Grade)      2.0     324.472829     162.236415     1.863479  0.155312
Residual   2995.0  260747.835461      87.061047          NaN       NaN

> 학교의 p-value는 매우 작으므로, 학교간의 평균차이는 있다고 볼 수 있고, 학년의 p-value는 0.05를 넘으므로, 학년간의 차이는 유의미하지 않다고 볼 수 있다.


### **▼ 카이제곱 검정**
- 주로 범주형 자료 분석에 사용.
- 적합성 검정, 동질성 검정, 독립성 검정

**▶ 적합성 검정** 

In [104]:
# A 회사에서 출시되는 제품 공정 결과의 예를 보고, 색상과 관계없이 동일한 비율로 제품을 생산하는 지 적합성 검정을 수행하자

from scipy import stats

color = ['Black','Gold','Purple','Red', 'White']    # 색상(분석엔 필요 X)
counts = [423, 304, 274, 205, 294]                  # 수량
expected = 300                          # 기대도수(동일한 비율 = 1500/5)

print(stats.chisquare(counts, expected))        # f_obs=counts, f_exp=expected
print('> p-value가 0.05보다 작으므로 귀무가설을 기각. 색상별로 동일한 비율로 생산한다고 볼 수 없다.')

Power_divergenceResult(statistic=82.94, pvalue=4.14849046718008e-17)
> p-value가 0.05보다 작으므로 귀무가설을 기각. 색상별로 동일한 비율로 생산한다고 볼 수 없다.


**▶ 동질성 검정** 

In [111]:
# A 회사의 성별에 따른 제품 선호도조사의 예를 보고, 성별 간 선호도의 차이 검증을 위한 동질성 검정을 수행하자

from scipy import stats

cross = pd.DataFrame({"Good" : [400 , 350],"Bad" : [350, 800]}, index=['남성', '여성'])
display(cross)

print(stats.chi2_contingency(cross))
chi, pvalue, df, expected = stats.chi2_contingency(cross)   # 카이제곱통계량, 유의확률, 자유도, 기대빈도
print('> p-value가 0.05보다 작으므로 귀무가설 기각. 성별 간 선호도의 차이가 있다고 볼 수 있다.')

Good  Bad
남성   400  350
여성   350  800

(98.66917336693975, 2.984113573360021e-23, 1, array([[296.05263158, 453.94736842],
       [453.94736842, 696.05263158]]))
> p-value가 0.05보다 작으므로 귀무가설 기각. 성별 간 선호도의 차이가 있다고 볼 수 있다.


**▶ 독립성 검정** 

In [115]:
# A 회사의 출시된 제품의 한 달 간 판매량의 예이다. 이를 통해 성별과 색상이 서로 관련이 있는 지 알아보기 위해 독립성 검정을 수행하자.
from scipy import stats

cross = pd.DataFrame({'Black' : [1620, 2380],'Gold' : [385, 615],'Purple' : [778, 1230],'Red' : [394, 610],'White' : [800, 180]}, index=['남성', '여성'])
display(cross)

chi, pvalue, df, expected = stats.chi2_contingency(cross)
print('카이제곱통계량: ', chi)
print('pvalue: ', pvalue)
print('> p-vale가 0.05보다 작으므로 귀무가설을 기각. 성별과 색상은 독립성이 없다 즉, 종속적이고 관련이 있다.')
print('자유도: ', df, '\n 기대빈도: \n', expected)

Black  Gold  Purple  Red  White
남성   1620   385     778  394    800
여성   2380   615    1230  610    180

카이제곱통계량:  626.2830361414021
pvalue:  3.1731601033660286e-134
자유도:  4 
 기대빈도: 
 [[1769.12811388  442.28202847  888.10231317  444.05115658  433.4363879 ]
 [2230.87188612  557.71797153 1119.89768683  559.94884342  546.5636121 ]]


**● 교차표 만드는 법**   
pd.crosstab(index, columns)

In [118]:
display(titanic.head())
pd.crosstab(titanic['sex'], titanic['embark_town'])

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  요금_대중소  
0    man        True  NaN  Southampton    no  False     low  
1  woman       False    C    Cherbourg   yes  False    high  
2  woman       False  NaN  Southampton   yes   True     low  
3  woman       False    C  Southampton   yes  False  middle  
4    man        True  NaN  Southampton    no   True     low

embark_town  Cherbourg  Queenstown  Southampton
sex                                            
female              73          36          203
male                95          41          441

### **▼ 비모수 검정**
- 모수적 검정은 가설 검정 시 분포를 가정하기 때문에, 실제 데이터가 가정한 분포와 이질적일수록 잘못된 결론을 내릴 가능성이 높다.
- 실제로는 정규성 검정을 선행하여 정규성을 만족하면 모수적 검정, 정규성을 만족하지 않으면 비모수적 검정을 해야 한다.

**▶ 스피어만 상관계수** 

In [120]:
from sklearn.datasets import load_diabetes
from scipy import stats

diabetes = pd.DataFrame(load_diabetes()['data'], columns=load_diabetes()['feature_names'])
display(diabetes.head(2))

print(stats.spearmanr(diabetes['sex'], diabetes['bmi']))
print('> 상관계수 0.098로 서로 상관관계가 적다고 볼 수 있다. 다만, p-value는 0.05보다 낮으므로 귀무가설을 기각, 상관계수는 작지만 유의하다는 것을 확인할 수 있다.')

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204

SpearmanrResult(correlation=0.09807947297621517, pvalue=0.03929011358104615)
> 상관계수 0.098로 서로 상관관계가 적다고 볼 수 있다. 다만, p-value는 0.05보다 낮으므로 귀무가설을 기각, 상관계수는 작지만 유의하다는 것을 확인할 수 있다.


**▶ 켄달의 타우 검정** 

In [123]:
# 두 개의 등수 데이터를 임의로 생성하고 두 순위 간 상관관계가 있는지 검정하자.

from scipy import stats

x = np.array([5, 4, 3, 6, 1, 2])
y = np.array([1, 5, 2, 2, 2, 6])

print(stats.kendalltau(x, y))
print('> 상관계수가 -0.298로 순위 간 상관관계가 거의 없는 것으로 확인된다.')    # 스피어만 상관계수 검정은 켄탈 타우 검정과 마찬가지로 순위 데이터에 대해서도 검정을 할 수 있다!

KendalltauResult(correlation=-0.29814239699997197, pvalue=0.4205962375999267)
> 상관계수가 -0.298로 순위 간 상관관계가 거의 없는 것으로 확인된다.


**▶ 윌콕슨의 부호순위 검정** 

In [130]:
from scipy import stats

# 단일표본 t-검정 대신 일표본 부호순위 검정
kg = np.array([75.5, 83.9, 75.7, 56.2, 73.4, 67.7, 79.0, 50.7, 58.4, 74.1, 65.1, 77.8, 48.1, 46.3])

print(stats.wilcoxon(kg - 70))
print('> 귀무가설 채택. 모집단의 중위수는 70과 같다고 할 수 있다.')

 # 대응표본 t-검정 대신 이표본 부호순위 검정
female = np.array([50.7, 58.4, 74.1, 65.1, 77.8, 48.1, 46.3])      
male = np.array([75.5, 83.9, 75.7, 56.2, 73.4, 67.7, 79.0])

print(stats.wilcoxon(female, male))
print('> 귀무가설 채택. 둘의 중앙값에 유의한 차이가 없다.')

WilcoxonResult(statistic=42.0, pvalue=0.5416259765625)
> 귀무가설 채택. 모집단의 중위수는 70과 같다고 할 수 있다.
WilcoxonResult(statistic=5.0, pvalue=0.15625)
> 귀무가설 채택. 둘의 중앙값에 유의한 차이가 없다.


**▶ 윌콕슨의 순위합 검정** 

In [129]:
# 독립표본 t-검정 대신 순위합 검정
from scipy import stats

print(stats.ranksums(female, male))
print('> 귀무가설 채택. 두 표본의 중앙값에 유의한 차이가 없다.')

RanksumsResult(statistic=-1.8527420384998257, pvalue=0.06391934147515746)
> 귀무가설 채택. 두 표본의 중앙값에 유의한 차이가 없다.


**▶ 만-위트니 U 검정** 

In [132]:
# 독립표본 t-검정 대신 만-위트니 U 검정
from scipy import stats

print(stats.mannwhitneyu(female, male))
print('> 귀무가설 채택. 두 표본의 중앙값에 유의한 차이가 없다.')

MannwhitneyuResult(statistic=10.0, pvalue=0.07284382284382285)
> 귀무가설 채택. 두 표본의 중앙값에 유의한 차이가 없다.


**▶ 크루스칼-왈리스 H 검정** 

In [143]:
# 일원배치 분산분석 대신
from scipy import stats

df = pd.read_csv('samples/예제/school_score.csv')
display(df.head(2))

final_A = df.loc[df['School'] == 'A']['Final'].values
final_B = df.loc[df['School'] == 'B']['Final'].values
final_C = df.loc[df['School'] == 'C']['Final'].values
print(stats.kruskal(final_A, final_B, final_C))
print('> 귀무가설 기각. 학교 간 기말고사 성적에는 유의미한 차이가 있다.')

id School Sex  Grade  Final
0   1      A   M      1   44.4
1   2      A   M      2   47.7

KruskalResult(statistic=1978.1734792103248, pvalue=0.0)
> 귀무가설 기각. 학교 간 기말고사 성적에는 유의미한 차이가 있다.


# 통계모형 - 선형 회귀모형

# 머신러닝 - 지도학습
- 선형 모델
- 서포트 벡터 머신
- 나이브베이즈
- K-최근접이웃
- 신경망
- 의사결정나무
- 앙상블

### **▼ 데이터 분할**

**▶ 홀드아웃** 

In [7]:
from sklearn.model_selection import train_test_split

train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.75, shuffle=True, stratify=None, random_state=None)
# stratify=Y 은 Y를 기준으로 층화추출하는 것. 목표 레이블 비율에 맞게 데이터를 분할하고자 할 때 사용.

**▶ K-Fold** 

In [10]:
from sklearn.model_selection import KFold

kfold = KFold(5)    # n_splits=5, shuffle=False
kfold.split(X, Y)

from sklearn.model_selection import StratifiedKFold     # 층화추출 K-Fold

skfold = StratifiedKFold(5)     # n_splits=5, shuffle=False
skfold.split(X, Y)

### **▼ 성과 분석**

**▶ 분류 지표** 

In [10]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_curve, auc

# val_Y = [0, 0, 0, 1, 1, 2, 2, 2, 2]
# predicted = [0, 1, 1, 1, 0, 0, 1, 2, 2]
val_Y = [0, 0, 0, 1, 1, 1]
predicted = [0, 1, 0, 1, 1, 1]

print(classification_report(val_Y, predicted))
print(f1_score(val_Y, predicted))
fpr, tpr, thresholds = roc_curve(val_Y, predicted)
print(auc(fpr, tpr))

              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.75      1.00      0.86         3

    accuracy                           0.83         6
   macro avg       0.88      0.83      0.83         6
weighted avg       0.88      0.83      0.83         6

0.8571428571428571
0.8333333333333334


**▶ 예측 지표** 

In [9]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error, r2_score

### **▼ 선형 모델**

**▶ 다중 선형 회귀모형** 

In [47]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes

X = pd.DataFrame(load_diabetes()['data'], columns=load_diabetes()['feature_names'])[['bmi', 'bp', 's1', 's2', 's3']]
Y = pd.DataFrame(load_diabetes()['target'], columns=['target'])

model = LinearRegression()
model.fit(X, Y)

print('계수: ', model.coef_)
print('절편: ', model.intercept_)
print(r2_score(Y, model.predict(X)))
print(model.score(X, Y))            # 사이킷런의 회귀분석은 모형의 통계적 유의성이나 회귀계수의 유의성을 제공하지 않아서, statsmodels를 쓰는게 더 다양하다.

계수:  [[ 608.9434702   301.13217977  990.86949656 -938.98139897 -597.46405077]]
절편:  [152.13348416]
0.47721326169685596
0.47721326169685596


**▶ 릿지 회귀** 

In [49]:
from sklearn.linear_model import Ridge
from sklearn.datasets import load_diabetes

X = pd.DataFrame(load_diabetes()['data'], columns=load_diabetes()['feature_names'])[['bmi', 'bp', 's1', 's2', 's3']]
Y = pd.DataFrame(load_diabetes()['target'], columns=['target'])

model = Ridge(0.1)  # alpha=1   / 릿지의 알파는  규제 강도를 제어하는 L2항에 곱하는 상수로, 0~무한대까지 가능하며, 0일 경우 규제항이 없는 일반적인 선형회귀가 됨.
model.fit(X, Y)

print('계수: ', model.coef_)
print('절편: ', model.intercept_)
print(r2_score(Y, model.predict(X)))

계수:  [[ 595.99217991  339.09043254  397.33941231 -338.99997282 -406.34685926]]
절편:  [152.13348416]
0.4576889481357329


**▶ 라쏘 회귀** 

In [51]:
from sklearn.linear_model import Lasso

model = Lasso(0.5)     # alpha=1, fit_intercept=True   / 규제 강도를 제어하는 L1항에 곱하는 상수. 0~무한대가 가능하며, 0일 경우 규제항이 없는 일반적인 선형회귀가 됨.
model.fit(X, Y)

print('계수: ', model.coef_)
print('절편: ', model.intercept_)
print(r2_score(Y, model.predict(X)))        # 결과를 보면 0이 있다. 이를 통해 라쏘 회귀모형은 중요한 변수를 선택하는 역할을 수행할 수 있음을 알 수 있다.

계수:  [ 574.0437769   237.23009748    0.            0.         -165.17218128]
절편:  [152.13348416]
0.39524439294179814


In [60]:
# exam p.258
X = pd.DataFrame(load_diabetes()['data'], columns=load_diabetes()['feature_names'])[['bmi', 'bp', 's1', 's2', 's3']]
Y = pd.DataFrame(load_diabetes()['target'], columns=['target'])

train_X = X.loc[:310]; val_X = X.loc[310:]; train_Y = Y.loc[:310]; val_Y = Y.loc[310:]      # 왜 loc로 인덱싱할 때랑 그냥 인덱싱할 때랑 차이가 있지??
#train_X = X[:310]; val_X = X[310:]; train_Y = Y[:310]; val_Y = Y[310:]
model= Lasso(0.5)
model.fit(train_X, train_Y)
print('계수: ', model.coef_)
print('절편: ', model.intercept_)
print(r2_score(val_Y, model.predict(val_X)))

계수:  [ 594.71505474  203.35253134    0.            0.         -145.53698093]
절편:  [150.89548632]
0.42182483358045586


**▶ 로지스틱 회귀** 

In [149]:
# 선형 회귀모델과는 다르게 로지스틱 회귀모형은 릿지와 라쏘를 함께 지원한다.
# LogisticRegression(penalty='l2', C=1, multi_class='auto', max_iter=100)   / penalty='l2', 'l1', 'none'  C=1 규제상수  max_iter=100 수렴할 때까지 걸리는 최대 반복 횟수
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

X = pd.DataFrame(load_breast_cancer()['data'], columns=load_breast_cancer()['feature_names'])
Y = load_breast_cancer()['target']
train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.8, random_state=2205, stratify=Y)

model = LogisticRegression(C=0.5, max_iter=2000)
model.fit(train_X, train_Y)

predicted = model.predict(val_X)
print('정확도: ', accuracy_score(val_Y, predicted))
fpr, tpr, thresholds = roc_curve(val_Y, model.predict_proba(val_X)[:, 1])   # predict_proba는 열이 2개인데 첫번째 열은 0이 될 확률이고, 두번째 열은 1이 될 확률이다.
print('auc: ', auc(fpr, tpr))

정확도:  0.9824561403508771
auc:  0.9983465608465608


In [148]:
# exam p.261
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X = pd.DataFrame(load_iris()['data'], columns=load_iris()['feature_names'])
Y = load_iris()['target']
train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.8, stratify=Y, random_state=2205)

model = LogisticRegression(C=0.05, max_iter=200)
model.fit(train_X, train_Y)

predicted = model.predict(val_X)
print('macro f1-score는 \n', classification_report(val_Y, predicted))
print(f1_score(val_Y, predicted, average='macro'))      # average='binary'  ['micro', 'macro', 'weighted', 'samples']

macro f1-score는 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

0.9665831244778613


### **▼ SVM　　서포트 벡터 머신**

**▶ SVC** - 이진분류

In [147]:
# SVC(C=1, kernel='rbf', gamma='scale') C는 규제화 매개변수로, 적을수록 규제가 강함. kernel은 커널유형으로, linear, poly, rbf, sigmoid가 가능. gamma는 rbf, poly, sigmoid에 대한 커널계수
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, roc_curve, auc
from sklearn.datasets import load_breast_cancer

X = pd.DataFrame(load_breast_cancer()['data'], columns=load_breast_cancer()['feature_names'])
Y = load_breast_cancer()['target']
train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.8, random_state=2205, stratify=Y)

model = SVC(probability=True, kernel='linear', C=0.5)
model.fit(train_X, train_Y)

predicted = model.predict(val_X)
print('정확도: ', accuracy_score(val_Y, predicted))
fpr, tpr, thresholds = roc_curve(val_Y, model.predict_proba(val_X)[:, 1])
print('auc: ', auc(fpr, tpr))

정확도:  0.9912280701754386
auc:  0.9983465608465608


**▶ LinearSVC** - 다지분류

In [146]:
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score
from sklearn.datasets import load_iris

X = pd.DataFrame(load_iris()['data'], columns=load_iris()['feature_names'])
Y = load_iris()['target']
train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.8, random_state=2205, stratify=Y)

model = LinearSVC()
model.fit(train_X, train_Y)

predicted = model.predict(val_X)
print('정확도: ', accuracy_score(val_Y, predicted))
print('macro f1-score: ', f1_score(val_Y, predicted, average='macro'))

정확도:  0.9666666666666667
macro f1-score:  0.9665831244778613


c:\Users\ALT\anaconda3\envs\bbg\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


**▶ SVR, LinearSVR** - 연속형

In [140]:
# SVR(C=1, epsilon=0.1 kernel='rbf', gamma='scale')
# LinearSVR(C=1, loss='epsilon_insensitive')
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR, LinearSVR
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.datasets import load_diabetes

X = pd.DataFrame(load_diabetes()['data'], columns=load_diabetes()['feature_names'])
Y = load_diabetes()['target']
train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.8, random_state=2205)

model = SVR()
model.fit(train_X, train_Y)
model2 = LinearSVR()
model2.fit(train_X, train_Y)

predicted = model.predict(val_X)
print('RMSE: ', np.sqrt(mean_squared_error(val_Y, predicted)))
print('R2: ', r2_score(val_Y, predicted))

predicted = model2.predict(val_X)
print('RMSE: ', np.sqrt(mean_squared_error(val_Y, predicted)))
print('R2: ', r2_score(val_Y, predicted))

RMSE:  76.61319796718303
R2:  0.07558358226529283
RMSE:  99.64577466531667
R2:  -0.5637893235592495


### **▼ 나이브베이즈**

**▶ BernoulliNB** - 이진 분류

In [139]:
# BernoulliNB(alpha=1)
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score, roc_curve, auc
from sklearn.datasets import load_breast_cancer

X = pd.DataFrame(load_breast_cancer()['data'], columns=load_breast_cancer()['feature_names'])
Y = load_breast_cancer()['target']
train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.8, random_state=2205, stratify=Y)

model = BernoulliNB()
model.fit(train_X, train_Y)

predicted = model.predict(val_X)
print('정확도: ', accuracy_score(val_Y, predicted))
fpr, tpr, thresholds = roc_curve(val_Y, model.predict_proba(val_X)[:, 1])
print('auc: ', auc(fpr, tpr))

정확도:  0.631578947368421
auc:  0.5347222222222222


**▶ MultinomialNB** - 다지 분류

In [138]:
# MultinomialNB(alpha=1)
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, roc_curve, auc, f1_score
from sklearn.datasets import load_iris

X = pd.DataFrame(load_iris()['data'], columns=load_iris()['feature_names'])
Y = load_iris()['target']
train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.8, random_state=2205, stratify=Y)

model = MultinomialNB()
model.fit(train_X, train_Y)

predicted = model.predict(val_X)
print('정확도: ', accuracy_score(val_Y, predicted))
print('macro f1-score: ', f1_score(val_Y, predicted, average='macro'))

정확도:  0.9666666666666667
macro f1-score:  0.9665831244778613


**▶ GaussianNB** - 연속형

In [137]:
# GaussianNB(var_smoothing=1)
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.datasets import load_diabetes

X = pd.DataFrame(load_diabetes()['data'], columns=load_diabetes()['feature_names'])
Y = load_diabetes()['target']
train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.8, random_state=2205)

model = GaussianNB()
model.fit(train_X, train_Y)

predicted = model.predict(val_X)
print('RMSE: ', np.sqrt(mean_squared_error(val_Y, predicted)))
print('R2: ', r2_score(val_Y, predicted))

RMSE:  78.87808826910528
R2:  0.020119261810313316


### **▼ K-최근접이웃**

In [152]:
# KNeighborsClassifier(n_neighbors=5, weights='uniform')
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, roc_curve, auc, f1_score, confusion_matrix, classification_report
from sklearn.datasets import load_breast_cancer

X = pd.DataFrame(load_breast_cancer()['data'], columns=load_breast_cancer()['feature_names'])
Y = load_breast_cancer()['target']
train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.8, random_state=2205, stratify=Y)

model = KNeighborsClassifier(5, weights='distance')
model.fit(train_X, train_Y)

print('정확도: ', accuracy_score(val_Y, model.predict(val_X)))
fpr, tpr, thresholds = roc_curve(val_Y, model.predict_proba(val_X)[:, 1])
print('auc: ', auc(fpr, tpr))

정확도:  0.9824561403508771
auc:  0.9993386243386244


In [157]:
from sklearn.datasets import load_iris

X = pd.DataFrame(load_iris()['data'], columns=load_iris()['feature_names'])
Y = load_iris()['target']
train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.8, random_state=2205, stratify=Y)

model = KNeighborsClassifier()
model.fit(train_X, train_Y)

print('정확도: ', accuracy_score(val_Y, model.predict(val_X)))
print('macro f1_score: ', f1_score(val_Y, model.predict(val_X), average='macro'))

정확도:  1.0
macro f1_score:  1.0


In [160]:
# KNeighborsRegressor(n_neighbors=5, weights='uniform')
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.datasets import load_diabetes

X = pd.DataFrame(load_diabetes()['data'], columns=load_diabetes()['feature_names'])
Y = load_diabetes()['target']
train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.8, random_state=2205)

model = KNeighborsRegressor(5, weights='distance')
model.fit(train_X, train_Y)

predicted = model.predict(val_X)
print('RMSE: ', np.sqrt(mean_squared_error(val_Y, predicted)))
print('R2: ', r2_score(val_Y, predicted))

RMSE:  64.34099075385271
R2:  0.3480174738117894


### **▼ 신경망**

In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
from sklearn.neural_network import MLPRegressor

### **▼ 의사결정나무**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.tree import DecisionTreeRegressor

### **▼ 앙상블**

In [ ]:
from sklearn.ensemble import BaggingClassifier, BaggingRegressor

In [ ]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

In [ ]:
from sklearn.ensemble import AdaBoostClassifier, AdaBoostRegressor

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor

In [ ]:
from xgboost import XGBClassifier, XGBRegressor

In [ ]:
from lightgbm import LGBMClassifier, LGBMRegressor

# 머신러닝 - 군집 모형

### **▼ 군집 평가**

**▶ 실루엣 계수**
- silhouette_score: 전체 개체에 대한 실루엣 계수의 평균을 계산
- silhouette_samples: 각 개체에 대한 개별 실루엣계수를 계산

In [ ]:
from sklearn.metrics import silhouette_score, silhouette_samples

**▶ 랜드지수, 조정 랜드지수　 RI, ARI**

In [17]:
from sklearn.metrics import rand_score, adjusted_rand_score

val_Y = [0, 0, 0, 1, 1, 1, 1, 2, 2]
predicted = [0, 0, 1, 1, 1, 1, 2, 2, 2]

print('ri: ', rand_score(val_Y, predicted))
print('ari: ', adjusted_rand_score(val_Y, predicted))

ri:  0.7222222222222222
ari:  0.3076923076923077


### **▼ 계층적 군집분석**

In [25]:

from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import rand_score, adjusted_rand_score
from sklearn.datasets import load_iris

X = pd.DataFrame(load_iris()['data'], columns=load_iris()['feature_names'])
Y = load_iris()['target']

model_ward = AgglomerativeClustering(3)
res_ward = model_ward.fit_predict(X)

model_average = AgglomerativeClustering(3, linkage='average')
res_average = model_average.fit_predict(X)

model_complete = AgglomerativeClustering(3, linkage='complete')
res_complete = model_complete.fit_predict(X)

model_single = AgglomerativeClustering(3, linkage='single')
res_single = model_single.fit_predict(X)

print('RI 비교: ')
print(rand_score(Y, res_ward), rand_score(Y, res_average), rand_score(Y, res_complete), rand_score(Y, res_single), sep='\n')
print('ARI 비교: ')
print(adjusted_rand_score(Y, res_ward), adjusted_rand_score(Y, res_average), adjusted_rand_score(Y, res_complete), adjusted_rand_score(Y, res_single), sep='\n')

RI 비교: 
0.8797315436241611
0.8922595078299776
0.8367785234899329
0.7766442953020134
ARI 비교: 
0.7311985567707746
0.7591987071071522
0.6422512518362898
0.5637510205230709


### **▼ k-means 군집분석**

In [35]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, silhouette_samples
from sklearn.datasets import load_iris

X = pd.DataFrame(load_iris()['data'], columns=load_iris()['feature_names'])

model_2 = KMeans(2, random_state=2022)
model_2.fit(X)
predicted = model_2.predict(X)
print('전체 실루엣 계수 평균: ', silhouette_score(X, predicted))
ss = silhouette_samples(X, predicted)
ss_df = pd.DataFrame({'labels': predicted, 'silhouette': ss})
display(ss_df.groupby('labels').mean())

model_3 = KMeans(3, random_state=2022)
model_3.fit(X)
predicted = model_3.predict(X)
print('전체 실루엣 계수 평균: ', silhouette_score(X, predicted))
ss = silhouette_samples(X, predicted)
ss_df = pd.DataFrame({'labels': predicted, 'silhouette': ss})
display(ss_df.groupby('labels').mean())

model_4 = KMeans(4, random_state=2022)
predicted = model_4.fit_predict(X)
print('전체 실루엣 계수 평균: ', silhouette_score(X, predicted))
ss = silhouette_samples(X, predicted)
ss_df = pd.DataFrame({'labels': predicted, 'silhouette': ss})
display(ss_df.groupby('labels').mean())
# 전체 실루엣 계수의 평균이 1에 가까우면서, 라벨간의 평균의 편차가 적어야 좋은 군집임.

전체 실루엣 계수 평균:  0.6810461692117462


silhouette
labels            
0         0.632701
1         0.769526

전체 실루엣 계수 평균:  0.5528190123564095


silhouette
labels            
0         0.798140
1         0.417320
2         0.451105

전체 실루엣 계수 평균:  0.49805050499728737


silhouette
labels            
0         0.362998
1         0.763176
2         0.419518
3         0.321324

<br>
<br>

연습문제

<br><br>

In [147]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

X = pd.read_csv('samples/연습문제/FIFA_X_train.csv', encoding='cp949', index_col=0).drop(['Nationality', 'Club', 'Position', 'Age', 'Jersey_Number'], axis=1)
Y = pd.read_csv('samples/연습문제/FIFA_y_train.csv', encoding='cp949', index_col=0)
df = pd.concat((X, Y), axis=1)
df = df.dropna(subset=['Weight_lb'])
df['Height_cm'] = df['Height'].apply(lambda x: int(x.split("'")[0])*30 + int(x.split("'")[1])*2.5) # 키
#### df = df.loc[~(df['Age'] == '2*') & ~(df['Age'] == '3*') & ~(df['Age'] == '1*')]
df['Preferred_Foot'] = df['Preferred_Foot'].apply(lambda x: 0 if x == 'Left' else 1)        # 왼발오른발
df = pd.concat((df, pd.get_dummies(df['Position_Class'])), axis=1).drop('Position_Class', axis=1)   # 원핫
df = pd.concat((df, pd.get_dummies(df['Work_Rate'])), axis=1).drop('Work_Rate', axis=1)             # 원핫
# print(df.shape)
# display(df.head(3))
# print(df.info())
#print(df['Age'].value_counts())
#print(len(df['Wage'].unique()), df['Wage'].unique())
X = df.drop(['Value', 'Height'], axis=1); Y = df['Value']
train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.8, random_state=42)

model = RandomForestClassifier(random_state=42)
#model.fit(X, Y)
model.fit(train_X, train_Y)

predicted = model.predict(val_X)
print('rmse: ', np.sqrt(mean_squared_error(val_Y, predicted)))
print('r2: ', r2_score(val_Y, predicted), ' 훈련r2: ', model.score(train_X, train_Y), r2_score(train_Y, model.predict(train_X)))

df = pd.read_csv('samples/연습문제/FIFA_X_test.csv', encoding='cp949', index_col=0).drop(['Nationality', 'Club', 'Position', 'Age', 'Jersey_Number'], axis=1)
print(df.isnull().sum())
df['Height_cm'] = df['Height'].apply(lambda x: int(x.split("'")[0])*30 + int(x.split("'")[1])*2.5) # 키
df['Preferred_Foot'] = df['Preferred_Foot'].apply(lambda x: 0 if x == 'Left' else 1)        # 왼발오른발
df = pd.concat((df, pd.get_dummies(df['Position_Class'])), axis=1).drop('Position_Class', axis=1)   # 원핫
df = pd.concat((df, pd.get_dummies(df['Work_Rate'])), axis=1).drop('Work_Rate', axis=1)             # 원핫
df = df.drop(['Height'], axis=1)

res = model.predict(df)
#print(df.index)
res = pd.DataFrame(res, index=df.index, columns=['Value'])
res.to_csv('./temp.csv')

res = pd.read_csv('./temp.csv', index_col=0)
display(res.head())
res_real = pd.read_csv('samples/연습문제/FIFA_y_test.csv', encoding='cp949', index_col=0)
print('진짜 rmse: ', np.sqrt(mean_squared_error(res_real, res)))
print('진짜 r2: ', r2_score(res_real, res))

# model = RandomForestClassifier(random_state=42, oob_score=True)

rmse:  1719.9379168089336
r2:  0.8538625271126741  훈련r2:  1.0 1.0
Overall                   0
Preferred_Foot            0
Work_Rate                 0
Position_Class          509
Contract_Valid_Until      0
Height                    0
Height_cm               188
Weight_lb                 0
Release_Clause            0
Wage                      0
dtype: int64


Value
ID           
137351   3600
207707   6000
242101    575
200104  26500
244229    650

진짜 rmse:  2886.7356185231097
진짜 r2:  0.801068381761349


In [180]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_curve, auc, f1_score, confusion_matrix

X = pd.read_csv('samples/연습문제/College_X_train.csv', index_col=0).drop('Name', axis=1)
test_X = pd.read_csv('samples/연습문제/College_X_test.csv', index_col=0).drop('Name', axis=1)
Y = pd.read_csv('samples/연습문제/College_y_train.csv', index_col=0)   # Yes 452 / No 169
Y['Private'] = Y['Private'].map({'Yes': 1, 'No': 0}) 
print(X.head(2))
print(X.info())
# for i in X.columns:
#     print(i, '\t',len(X[i].unique()))

train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.7, random_state=42)

model = RandomForestClassifier()
model.fit(train_X, train_Y)

predicted = model.predict(val_X)
print('정확도: ', accuracy_score(val_Y, predicted))
fpr, tpr, thresholds = roc_curve(val_Y, model.predict_proba(val_X)[:, 1])
print('auc: ', auc(fpr, tpr))
print('혼동행렬: \n', confusion_matrix(val_Y, predicted))

res = model.predict(test_X)
res = pd.DataFrame(res, index=test_X.index, columns=['prob_Private'])
res.to_csv('./temp.csv')

res = pd.read_csv('./temp.csv', index_col=0)
print(res.head())
real_res = pd.read_csv('samples/연습문제/College_y_test.csv', index_col=0)
real_res['Private'] = real_res['Private'].map({'Yes': 1, 'No': 0}) 
print('진짜 정확도: ', accuracy_score(real_res, res))
fpr, tpr, thresholds = roc_curve(real_res, model.predict_proba(test_X)[:, 1])
print('진짜 auc: ', auc(fpr, tpr))
print('진짜 혼동행렬: \n', confusion_matrix(real_res, res))

     Apps  Accept  Enroll  Top10perc  Top25perc  F.Undergrad  P.Undergrad  \
ID                                                                          
681  2850    2044    1046         20         50         9260         1387   
746  2702    1623     604          7         24         2315          146   

     Outstate  Room.Board  Books  Personal  PhD  Terminal  S.F.Ratio  \
ID                                                                     
681      4652        2470    500       500   78        99       18.7   
746      5918        3755    500      2050   76        79       19.4   

     perc.alumni  Expend  Grad.Rate  
ID                                   
681           23    5917         45  
746            4    4599         52  
<class 'pandas.core.frame.DataFrame'>
Int64Index: 621 entries, 681 to 381
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Apps         621 non-null    int64  
 1   Accept      

C:\Users\ALT\AppData\Local\Temp\ipykernel_13300\553946578.py:17: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(train_X, train_Y)


In [269]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_curve, auc, confusion_matrix

X = pd.read_csv('samples\연습문제\weatherAUS_X_train.csv').drop(['Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday', 'Cloud9am', 'Cloud3pm', 'Pressure9am', 'Pressure3pm', 'Humidity3pm', 'Temp3pm', 'WindSpeed3pm', 'WindGustSpeed'], axis=1)
test_X = pd.read_csv('samples\연습문제\weatherAUS_X_test.csv').drop(['Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday', 'Cloud9am', 'Cloud3pm', 'Pressure9am', 'Pressure3pm', 'Humidity3pm', 'Temp3pm', 'WindSpeed3pm', 'WindGustSpeed'], axis=1)
Y = pd.read_csv('samples\연습문제\weatherAUS_y_train.csv')  # No 8882 / Yes 2832
#display(X.head())
X = X.fillna(X.mean())
test_X = test_X.fillna(test_X.mean())
Y['RainTomorrow'] = Y['RainTomorrow'].map({'No': 0, 'Yes': 1})
# print(X.isnull().sum())
# print(test_X.isnull().sum())
# print(len(X['Location'].value_counts()))  # 49개 도시. 도시당 약 240개 데이터
# print(X.info())
#mean_table = X.groupby('Date').mean()  # 날짜별로 묶으면 널 없음.
# print(X.groupby('Date').max() - X.groupby('Date').mean()) # 날짜로 묶어봤는데 최대 최소 편차가 큰거 같기도
# print(X.groupby('Location').max() - X.groupby('Location').mean()) # 지역별로 묶으면 널이 좀..

train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.7, random_state=42)

model = RandomForestClassifier()
model.fit(train_X.drop('Date', axis=1), train_Y['RainTomorrow'])

predicted = model.predict(val_X.drop('Date', axis=1))
print('정확도: ', accuracy_score(val_Y['RainTomorrow'], predicted))
fpr, tpr, thresholds = roc_curve(val_Y['RainTomorrow'], model.predict_proba(val_X.drop('Date', axis=1))[:, 1])
print('auc: ', auc(fpr, tpr))
print('혼동행렬: \n', confusion_matrix(val_Y['RainTomorrow'], predicted))

res = model.predict_proba(test_X.drop('Date', axis=1))[:, 1]
res = pd.DataFrame(res, index=test_X['Date'], columns=['RainTomorrow_Prob'])
res.to_csv('./temp.csv')

res = pd.read_csv('./temp.csv')
res_real = pd.read_csv('samples\연습문제\weatherAUS_y_test.csv')
res_real['RainTomorrow'] = res_real['RainTomorrow'].map({'No': 0, 'Yes': 1})
fpr, tpr, thresholds = roc_curve(res_real['RainTomorrow'], res['RainTomorrow_Prob'])
print('진짜 auc: ', auc(fpr, tpr))
print('진짜 정확도: ', accuracy_score(res_real['RainTomorrow'], model.predict(test_X.drop('Date', axis=1))))

C:\Users\ALT\AppData\Local\Temp\ipykernel_13300\4130667396.py:9: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  X = X.fillna(X.mean())
C:\Users\ALT\AppData\Local\Temp\ipykernel_13300\4130667396.py:10: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  test_X = test_X.fillna(test_X.mean())


정확도:  0.7849217638691323
auc:  0.7609540909224204
혼동행렬: 
 [[2452  221]
 [ 535  307]]
진짜 auc:  0.7029902408882442
진짜 정확도:  0.7825336555056955


<br>

## 7회

<br>

In [304]:
from sklearn.preprocessing import StandardScaler
df = pd.read_csv('samples/기출복원/07회/test_score.csv', encoding='cp949')
df = df.dropna()
#print(df.groupby('연령대').size()) # 가장 많은 연령대는 20 880개
res = pd.DataFrame(df.loc[(df['연령대'] == 20) & (df['과목명'] == '기본간호학')]['과목별점수'])
#res = res.dropna()

scaler = StandardScaler()
scaled = scaler.fit_transform(res)
print(round(max(scaled)[0], 4))

res = df.loc[(df['연령대'] == 20) & (df['과목명'] == '기본간호학')]['과목별점수']
print((max(res) - np.mean(res)) / np.std(res))
print((max(res) - np.mean(res)) / np.std(res, ddof=1))
print(((res - res.mean()) / res.std()).max())

0.5991
0.5990785244426713
0.5962725206117928
0.5962725206117928


In [316]:
from sklearn.linear_model import LinearRegression
df = pd.read_csv('samples/기출복원/07회/diabetes.csv')
print(df.corr()['progression'].sort_values())

print(round(max(df['bmi']), 2))

s3            -0.394789
sex            0.043062
s2             0.174054
age            0.187889
s1             0.212022
s6             0.382483
s4             0.430453
bp             0.441482
s5             0.565883
bmi            0.586450
progression    1.000000
Name: progression, dtype: float64
0.17


In [331]:
df = pd.read_csv('samples/기출복원/07회/iris.csv')['sepal_length']
df = df.fillna(df.median())
iqr = df.quantile(0.75) - df.quantile(0.25)
print(res:=df.loc[(df < df.quantile(0.25) - (iqr*1.5)) | (df > df.quantile(0.75) + (iqr*1.5))])     # ★★★
print(len(res))

106    11.0
117     9.0
133     8.5
144     3.0
147     2.8
Name: sepal_length, dtype: float64
5


In [48]:
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv('samples/기출복원/07회/Flight_train.csv').drop('flight', axis=1)
test_X = pd.read_csv('samples/기출복원/07회/Flight_test.csv').drop('flight', axis=1)
df['class'] = df['class'].map({'Economy': 0, 'Business': 1})
df['stops'] = df['stops'].map({'zero': 0, 'one': 1, 'two_or_more': 2})
df = pd.concat((df, pd.get_dummies(df[['airline', 'source_city', 'destination_city', 'arrival_time','departure_time']])), axis=1)
df = df.drop(['airline', 'source_city', 'destination_city', 'arrival_time','departure_time'], axis=1)
#print(df.info())    # 결측치없음. /class 'Economy' 'Business'] /stops 'one' 'zero' 'two_or_more'
# print(df.nunique())
# print(test_X.nunique())
scaler = StandardScaler()
# df_scaled = scaler.fit_transform(df[['duration', 'days_left']])
# df[['duration', 'days_left']] = df_scaled
df_scaled = scaler.fit_transform(df.drop('price', axis=1))
train_X, val_X, train_Y, val_Y = train_test_split(df_scaled, df['price'], train_size=0.9, random_state=42)

model = RandomForestRegressor(random_state=42)
model.fit(train_X, train_Y)
'''
[-0.91783263 -1.17154926]
 [-1.38417167 -1.02410514]
 [ 1.55670513 -0.50805072]
'''
predicted = model.predict(val_X)                # 정석스케일러 RMSE: 4383.348013196695 R2: 0.9636504461469366 /안함 RMSE: 4400.632090453199 R2: 0.9633632195042433
print('RMSE: ', np.sqrt(mean_squared_error(val_Y, predicted)))  # 전부 스케일링 RMSE:  4375.940869606868 R2:  0.9637731919899649
print('R2: ', r2_score(val_Y, predicted))
#---------------------------------------
test_X['class'] = test_X['class'].map({'Economy': 0, 'Business': 1})
test_X['stops'] = test_X['stops'].map({'zero': 0, 'one': 1, 'two_or_more': 2})
test_X = pd.concat((test_X, pd.get_dummies(test_X[['airline', 'source_city', 'destination_city', 'arrival_time','departure_time']])), axis=1)
test_X = test_X.drop(['airline', 'source_city', 'destination_city', 'arrival_time','departure_time'], axis=1)
test_X_scaled = scaler.transform(test_X)
#print(test_X.info())
res = model.predict(test_X_scaled)
res = pd.DataFrame(res, columns=['pred'])
print(res.head())
res.to_csv('./result.csv', index=False)
#------------------------------------
res = pd.read_csv('./result.csv')
res_real = pd.read_csv('samples/기출복원/07회/Flight_y_test.csv')
print('진짜 RMSE: ', np.sqrt(mean_squared_error(res_real, res)))    # train_size=0.7일 때, RMSE: 4680.018296243825  R2: 0.9580908113511515
print('진짜 R2: ', r2_score(res_real, res))

RMSE:  4613.517285388608
R2:  0.9610926881610016
       pred
0  11478.97
1   5078.12
2  13552.49
3  19694.78
4   2163.61
진짜 RMSE:  4536.22866916044
진짜 R2:  0.9606264993345255


In [86]:
import statsmodels.api as sm
from sklearn.metrics import accuracy_score
df = pd.read_csv('samples/기출복원/07회/StudentsPerformance.csv')
df['gender'] = df['gender'].map({'female': 0, 'male': 1})
df = pd.concat((df, pd.get_dummies(df['race'], drop_first=True)), axis=1)
df = df.drop('race', axis=1)
#print(df.info())
train_X = df.drop('gender', axis=1).iloc[:800]
train_Y = df['gender'].iloc[:800]
test_X = df.drop('gender', axis=1).iloc[800:]
test_Y = df['gender'].iloc[800:]

model = sm.GLM(train_Y, train_X, family=sm.families.Binomial()).fit()
print(model.summary())
print('Q1-1 - math score가 한 단위 증가할 때 오즈비를 구해라: ', round(np.exp(0.3770), 2))  # ★★★
print('Q1-2 - 잔차 이탈도를 구해라: ', 466.94)          # ★★★
res = model.predict(test_X)

print('Q1-3 - 평가용 데이터에서 모형의 오분류율을 구해라: ', round(1- accuracy_score(test_Y, np.round(res)), 2))

                 Generalized Linear Model Regression Results                  
Dep. Variable:                 gender   No. Observations:                  800
Model:                            GLM   Df Residuals:                      793
Model Family:                Binomial   Df Model:                            6
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -233.47
Date:                Thu, 20 Jun 2024   Deviance:                       466.94
Time:                        18:58:25   Pearson chi2:                     731.
No. Iterations:                     7   Pseudo R-squ. (CS):             0.5514
Covariance Type:            nonrobust                                         
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
math score        0.3770      0.027     14.064

In [91]:
round(12.5, 0)

12.0

In [93]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
df = pd.read_csv('samples/기출복원/07회/mtcars.csv')[['disp', 'hp', 'drat', 'wt', 'mpg']]
#print(df.info())
X = df[['disp', 'hp', 'drat', 'wt']]
Y = df['mpg']
print(df.corr()['mpg'])
print('2-1번 답: ', round(-0.867659, 3))

model = LinearRegression()
model.fit(X, Y)
print('계수: ', model.coef_)
print('2-2번 답 R2: ', round(r2_score(Y, model.predict(X)), 3))
print('2-3번 답: ', round(1.76804877, 3))

# 올바른 방법 -----------------
import statsmodels.api as sm
X = df[['disp', 'hp', 'drat', 'wt']]
Y = df['mpg']
X = sm.add_constant(X)

model = sm.OLS(Y, X).fit()
print(model.summary())
print('Q2-1 - 가장 높은 상관계수: ', round(abs(-0.867659), 3))
print('Q2-2 - 결정계수: ', 0.838)
print('Q2-3 - 독립변수 중 가장 유의하지 않은 변수의 회귀계수 추정값: ', round(0.0038, 3))

disp   -0.847551
hp     -0.776168
drat    0.681172
wt     -0.867659
mpg     1.000000
Name: mpg, dtype: float64
2-1번 답:  -0.868
계수:  [ 0.00381524 -0.03478353  1.76804877 -3.47966753]
2-2번 답 R2:  0.838
2-3번 답:  1.768
                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.838
Model:                            OLS   Adj. R-squared:                  0.814
Method:                 Least Squares   F-statistic:                     34.82
Date:                Thu, 20 Jun 2024   Prob (F-statistic):           2.70e-10
Time:                        19:05:29   Log-Likelihood:                -73.292
No. Observations:                  32   AIC:                             156.6
Df Residuals:                      27   BIC:                             163.9
Df Model:                           4                                         
Covariance Type:            nonrobust                                     

<br>

## 6회

<br>

In [125]:
df = pd.read_csv('samples/기출복원/06회/sejong_fire.csv', encoding='cp949')
df['접수일시'] = pd.to_datetime(df['접수일시'])
df['상황종료일시'] = pd.to_datetime(df['상황종료일시'])
df['화재진압시간'] = df['상황종료일시'] - df['접수일시']
# print(df.head())
# print(df.info())
print(df.sort_values('화재진압시간', ascending=False).head(3))      # 조치원119구조대
print('화재진압이 가장 오래걸린 서센터의 평균 화재진압시간: ', res:=df.loc[df['서센터명']=='조치원119구조대']['화재진압시간'].mean())
print('분수로: ', res.components.days, res.components.hours, res.components.minutes, '->', res.components.minutes+res.components.hours*60+res.components.days*60*24)
print(type(res))    # ★★★

      관할서명       서센터명  ...              상황종료일시           화재진압시간
54  조치원소방서  조치원119구조대  ... 2012-08-08 07:31:00 38 days 06:55:00
14  조치원소방서  조치원119구조대  ... 2012-07-31 22:39:00 30 days 22:06:00
15  조치원소방서  부강119안전센터  ... 2012-07-31 22:42:00 27 days 05:40:00

[3 rows x 6 columns]
화재진압이 가장 오래걸린 서센터의 평균 화재진압시간:  1 days 02:13:06.176470588
분수로:  1 2 13 -> 1573
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>


In [149]:
df = pd.read_csv('samples/기출복원/06회/busan_school_Info.csv', encoding='cp949')
df['sum'] = df['student_1'] + df['student_2'] + df['student_3'] + df['student_4'] + df['student_5'] + df['student_6']
df['rate'] = df['sum'] / df['teacher']
#print(df.info())
print(df.sort_values('rate', ascending=False).head())       # 동성초등학교
print(df.loc[df['school_name'] == '동성초등학교']['teacher'].values[0])

    school_name  student_1  student_2  ...  teacher   sum       rate
81       동성초등학교        112        128  ...       24   744  31.000000
14     부산삼육초등학교         60         64  ...       10   303  30.300000
42       동래초등학교        112        119  ...       22   619  28.136364
64       혜화초등학교         60         59  ...       12   327  27.250000
300      명원초등학교        223        371  ...       71  1759  24.774648

[5 rows x 10 columns]
24


In [204]:
#pd.set_option('display.max_rows', None)
df = pd.read_csv('samples/기출복원/06회/five_crime.csv', encoding='cp949')
df['연도'] = df['연월'].apply(lambda x: x.split('.')[0].replace(' ', '')[:4])
df['월'] = df['연월'].apply(lambda x: x.split('.')[1].strip()[:2])
df = df.drop('연월', axis=1)
df['총발생건수'] = df.iloc[:, 0:10].sum(axis=1)     # ★★★
#print(df.info())
print(df[['연도', '총발생건수', '폭력_검거건수']].groupby('연도').mean().sort_values('총발생건수', ascending=False)) # 2012년
print('답: ',round(4884.166667))
#pd.set_option('display.max_rows', 60)

             총발생건수      폭력_검거건수
연도                             
2012  18358.583333  4884.166667
2011  18203.250000  4974.833333
2009  18140.916667  5816.666667
2010  18096.166667  5046.750000
2013  17692.583333  4522.916667
2008  16730.166667  5922.916667
답:  4884


In [225]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

df = pd.read_csv('samples/기출복원/06회/Airline_train.csv')
test_X = pd.read_csv('samples/기출복원/06회/Airline_test.csv')
df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1})   # Ages ['[10, 20)' '[20, 30)' '[30, 40)' '[40, 49)' '[50, 59)']
df['Customer_Type'] = df['Customer_Type'].map({'NL': 0, 'L': 1})        # Class ['Eco Plus' 'Eco' 'Business']
Y = df['Satisfaction'].map({'No': 'Not satisfied', 'Yes': 'Satisfied'})
df = df.drop('Satisfaction', axis=1)
df = pd.get_dummies(df)
#print(df.info())
train_X, val_X, train_Y, val_Y = train_test_split(df, Y, train_size=0.9, random_state=42)

model = RandomForestClassifier(random_state=42)
model.fit(train_X, train_Y)

predicted = model.predict(val_X)
print('정확도: ', accuracy_score(val_Y, predicted))
print('혼동행렬: \n', confusion_matrix(val_Y, predicted))
print('f1_score: ', f1_score(val_Y, predicted, average='macro'))
# -------------------------------------
test_X['Gender'] = test_X['Gender'].map({'Female': 0, 'Male': 1})
test_X['Customer_Type'] = test_X['Customer_Type'].map({'NL': 0, 'L': 1})
test_X = pd.get_dummies(test_X)
res = model.predict(test_X)
res = pd.DataFrame(res, columns=['pred'])
print(res.head())
res.to_csv('./result.csv', index=False)
# -----------------------------------------
res = pd.read_csv('./result.csv')
res_real = pd.read_csv('samples/기출복원/06회/Airline_y_test.csv')
print('진짜 정확도: ', accuracy_score(res_real, res))
print('진짜 혼동행렬: \n', confusion_matrix(res_real, res))
print('진짜 f1_score: ', f1_score(res_real, res, average='macro'))

정확도:  0.9518633540372671
혼동행렬: 
 [[328  16]
 [ 15 285]]
f1_score:  0.9516477874091458
            pred
0  Not satisfied
1      Satisfied
2      Satisfied
3  Not satisfied
4  Not satisfied
진짜 정확도:  0.9336228287841191
진짜 혼동행렬: 
 [[839  44]
 [ 63 666]]
진짜 f1_score:  0.9328494149570878


In [238]:
import statsmodels.api as sm
from scipy import stats

df = pd.read_csv('samples/기출복원/06회/cancer.csv')
print(df.value_counts())
print('Q3-1 - 항암약의 "부작용없음"의 관찰도수는? ', df['x'].value_counts()['None'])

pd.DataFrame({'cancer': np.array([964, 627, 328, 81])/2000, 'cold': [0.05, 0.05, 0.10, 0.80]}, index=['1_Grade', '2_Grade', '3_Grade', 'None'])

x      
1_Grade    964
2_Grade    627
3_Grade    328
None        81
dtype: int64
Q3-1 - 항암약의 "부작용없음"의 관찰도수는?  81


cancer  cold
1_Grade  0.4820  0.05
2_Grade  0.3135  0.05
3_Grade  0.1640  0.10
None     0.0405  0.80