In [58]:
import numpy as np; import pandas as pd; p = print; import matplotlib.pyplot as plt; from sklearn.datasets import load_iris

# Python ~ Numpy ~ Pandas

**▶ range / reversed**

In [3]:
'''
range도 기본적으로 sequence형이라 iterable하게 쓸 수 있는 것이다.
    - 인덱싱과 슬라이싱 가능
'''
print(range(1, 11)[7])
print(range(1, 11)[3:7])    # range를 슬라이싱하면 range 객체로 나온다.
'''
reversed는 reversed 객체로 리턴됨.
'''
print(reversed('abcde'))
print(reversed([1, 2, 3 ,4, 5]))
print(reversed((1, 2, 3, 4, 5)))
print(reversed(range(10)))

8
range(4, 8)


**▶ ndarray**

In [28]:
'''
numpy 배열을 만들 때 dtype 인자를 사용하면 데이터 타입을 바꿀 수 있다.  ★
'''
print(arr:=np.array([3, 4, 5, 6], dtype='str'))
print(type(arr))
print(np.zeros((2, 4), dtype='float'))
print(np.full((2, 5), 9))       # 9로 채운 행렬 만들기
print(np.identity(3))           # 단위행렬
p()
arr = np.arange(1, 13).reshape(4, -1)
print(arr)
print(arr[-2, -2])
print(arr[-3:, 1:])
print(arr[1:3, :])

['3' '4' '5' '6']
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[9 9 9 9 9]
 [9 9 9 9 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
8
[[ 5  6]
 [ 8  9]
 [11 12]]
[[4 5 6]
 [7 8 9]]


In [40]:
# abs(numpy.ndarray)
arr = np.array([3, -4, -5, 6, 0])
print(np.abs(arr))
print(np.fabs(arr))     # 복소수가 아닌 경우에는 fabs로 빠르게 연산 가능하다고 함
print(np.sign(arr))     # 부호만 가져옴. 0의 부호는 0
'''넘파이 연산
     np.sqrt(arr)  np.square(arr)  np.exp(arr)  np.log(arr)  np.log10(arr)
     np.round(arr, 2)  np.ceil(arr)  np.floor(arr)'''
print(np.trunc([3.14, -4.15, -5.79, 6.88]))     # 일반적인 올림, 내림과는 다르게 소수점 파트를 삭제함.
'''형상 변환 
     arr.reshape()  arr.ravel() == arr.flatten()  arr.transpose()
   통계
     np.mean(arr)  np.min(arr)  np.max(arr)
     np.var(arr, ddof=None)  np.std(arr, ddof=None)     ← ddof = 자유도. 표본 통계량을 구할 때는 ddof=1을 줘야 함. ★
     np.argmin(arr)  np.argmax(arr)                    ★
'''; p()

[3 4 5 6 0]
[3. 4. 5. 6. 0.]
[ 1 -1 -1  1  0]
[ 3. -4. -5.  6.]



**▶ DataFrame**

In [53]:
'''
    pd.DataFrame(object, index, columns)
'''
df = pd.DataFrame({
    'Name': ['Olivia', 'Lucas', 'Sophia', 'Zoe', 'Aca', 'Elliot'],
    'Sex': ['F', 'M', 'F', 'F', 'F', 'M'],
    'Age': [22, 32, 27, 24, 38, 19]
}, index=list('abcdef'))
display(df)
print(df.iloc[3, 0])
print(df.loc['d', 'Age'])
print(df.iloc[2:5])
print(df.loc['c':'e'])      # loc는 마지막 슬라이싱 행이 포함됨. 지져스
print(df['Name']['c'], df['Name'][2])       # 인덱서 없이 인덱싱할 때는 열 → 행 순서. 걍 loc나 iloc 쓰자.

Name Sex  Age
a  Olivia   F   22
b   Lucas   M   32
c  Sophia   F   27
d     Zoe   F   24
e     Aca   F   38
f  Elliot   M   19

Zoe
24
     Name Sex  Age
c  Sophia   F   27
d     Zoe   F   24
e     Aca   F   38
     Name Sex  Age
c  Sophia   F   27
d     Zoe   F   24
e     Aca   F   38
Sophia Sophia


In [68]:
'''데이터 프레임의 통계
        df.describe()  df.count()  df.mean()  df.min()  df.max()
        df.var(ddof=1)  df.std(ddof=1)      ← 넘파이와는 다르게 ddof=1이 디폴트 ★
        df.median()  df.quantile(q=0.5)  df.mode()     ★

   입출력
        pd.read_csv(path, sep=',', encoding=None)
        pd.to_csv(path, index=True)

   정렬
        df.sort_values(by, ascending=True, axis=0)
        df.sort_index(axis=0, ascending=True, level=None)       ← axis=1이면 열 인덱스(특성 순서)을 정렬함

   순위
        df.rank(axis=0, method='average', ascending=True)

   컬럼 추가, 삭제, 구간화
        df['컬럼명'] = 추가할 컬럼
        df.insert(loc, column, value)
        df.drop(labels, axis=0)
        pd.cut(x, bins, labels=None, right=True)        ← 구간화(비닝, binning)
        pd.qcut(x, q, labels=None, right=True)          ← 분위수 기반의 구간화
'''
iris = pd.DataFrame(load_iris()['data'], columns=load_iris()['feature_names'])
iris['cut'] = pd.cut(iris['sepal length (cm)'], bins=5)
print(iris['cut'].unique())

[(5.02, 5.74], (4.296, 5.02], (5.74, 6.46], (6.46, 7.18], (7.18, 7.9]]
Categories (5, interval[float64, right]): [(4.296, 5.02] < (5.02, 5.74] < (5.74, 6.46] < (6.46, 7.18] < (7.18, 7.9]]
