In [29]:
import numpy as np; import pandas as pd; p = print; import matplotlib.pyplot as plt; from sklearn.datasets import load_iris; from seaborn import load_dataset

# Python ~ Numpy ~ Pandas

**▶ range / reversed**

In [3]:
'''
range도 기본적으로 sequence형이라 iterable하게 쓸 수 있는 것이다.
    - 인덱싱과 슬라이싱 가능
'''
print(range(1, 11)[7])
print(range(1, 11)[3:7])    # range를 슬라이싱하면 range 객체로 나온다.
'''
reversed는 reversed 객체로 리턴됨.
'''
print(reversed('abcde'))
print(reversed([1, 2, 3 ,4, 5]))
print(reversed((1, 2, 3, 4, 5)))
print(reversed(range(10)))

8
range(4, 8)


**▶ ndarray**

In [28]:
'''
numpy 배열을 만들 때 dtype 인자를 사용하면 데이터 타입을 바꿀 수 있다.  ★
'''
print(arr:=np.array([3, 4, 5, 6], dtype='str'))
print(type(arr))
print(np.zeros((2, 4), dtype='float'))
print(np.full((2, 5), 9))       # 9로 채운 행렬 만들기
print(np.identity(3))           # 단위행렬
p()
arr = np.arange(1, 13).reshape(4, -1)
print(arr)
print(arr[-2, -2])
print(arr[-3:, 1:])
print(arr[1:3, :])

['3' '4' '5' '6']
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[9 9 9 9 9]
 [9 9 9 9 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
8
[[ 5  6]
 [ 8  9]
 [11 12]]
[[4 5 6]
 [7 8 9]]


In [40]:
# abs(numpy.ndarray)
arr = np.array([3, -4, -5, 6, 0])
print(np.abs(arr))
print(np.fabs(arr))     # 복소수가 아닌 경우에는 fabs로 빠르게 연산 가능하다고 함
print(np.sign(arr))     # 부호만 가져옴. 0의 부호는 0
'''넘파이 연산
     np.sqrt(arr)  np.square(arr)  np.exp(arr)  np.log(arr)  np.log10(arr)
     np.round(arr, 2)  np.ceil(arr)  np.floor(arr)'''
print(np.trunc([3.14, -4.15, -5.79, 6.88]))     # 일반적인 올림, 내림과는 다르게 소수점 파트를 삭제함.
'''형상 변환 
     arr.reshape()  arr.ravel() == arr.flatten()  arr.transpose()
   통계
     np.mean(arr)  np.min(arr)  np.max(arr)
     np.var(arr, ddof=None)  np.std(arr, ddof=None)     ← ddof = 자유도. 표본 통계량을 구할 때는 ddof=1을 줘야 함. ★
     np.argmin(arr)  np.argmax(arr)                    ★
'''; p()

[3 4 5 6 0]
[3. 4. 5. 6. 0.]
[ 1 -1 -1  1  0]
[ 3. -4. -5.  6.]



**▶ DataFrame**

In [53]:
'''
    pd.DataFrame(object, index, columns)
'''
df = pd.DataFrame({
    'Name': ['Olivia', 'Lucas', 'Sophia', 'Zoe', 'Aca', 'Elliot'],
    'Sex': ['F', 'M', 'F', 'F', 'F', 'M'],
    'Age': [22, 32, 27, 24, 38, 19]
}, index=list('abcdef'))
display(df)
print(df.iloc[3, 0])
print(df.loc['d', 'Age'])
print(df.iloc[2:5])
print(df.loc['c':'e'])      # loc는 마지막 슬라이싱 행이 포함됨. 지져스
print(df['Name']['c'], df['Name'][2])       # 인덱서 없이 인덱싱할 때는 열 → 행 순서. 걍 loc나 iloc 쓰자.

Name Sex  Age
a  Olivia   F   22
b   Lucas   M   32
c  Sophia   F   27
d     Zoe   F   24
e     Aca   F   38
f  Elliot   M   19

Zoe
24
     Name Sex  Age
c  Sophia   F   27
d     Zoe   F   24
e     Aca   F   38
     Name Sex  Age
c  Sophia   F   27
d     Zoe   F   24
e     Aca   F   38
Sophia Sophia


In [68]:
'''데이터 프레임의 통계
        df.describe()  df.count()  df.mean()  df.min()  df.max()
        df.var(ddof=1)  df.std(ddof=1)      ← 넘파이와는 다르게 ddof=1이 디폴트 ★
        df.median()  df.quantile(q=0.5)  df.mode()     ★

   입출력
        pd.read_csv(path, sep=',', encoding=None)
        pd.to_csv(path, index=True)

   정렬
        df.sort_values(by, ascending=True, axis=0)
        df.sort_index(axis=0, ascending=True, level=None)       ← axis=1이면 열 인덱스(특성 순서)을 정렬함

   순위
        df.rank(axis=0, method='average', ascending=True)

   컬럼 추가, 삭제, 구간화
        df['컬럼명'] = 추가할 컬럼
        df.insert(loc, column, value)
        df.drop(labels, axis=0)
        pd.cut(x, bins, labels=None, right=True)        ← 구간화(비닝, binning)
        pd.qcut(x, q, labels=None, right=True)          ← 분위수 기반의 구간화
'''
iris = pd.DataFrame(load_iris()['data'], columns=load_iris()['feature_names'])
iris['cut'] = pd.cut(iris['sepal length (cm)'], bins=5)
print(iris['cut'].unique())

[(5.02, 5.74], (4.296, 5.02], (5.74, 6.46], (6.46, 7.18], (7.18, 7.9]]
Categories (5, interval[float64, right]): [(4.296, 5.02] < (5.02, 5.74] < (5.74, 6.46] < (6.46, 7.18] < (7.18, 7.9]]


# 데이터 인코딩

**▶ Label Encoding**

In [10]:
'''
- 단순하게 문자열 값을 숫자형 카테고리 값으로 일대일로 변환.
- 숫자가 대소의 의미를 가지게 되므로, 가급적 트리 계열과 같은 특정 머신러닝 알고리즘에서만 사용해야 한다.
- 넘파이의 select()나 판다스의 map()으로도 같은 기능 가능
'''
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({'Class': ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F']})
display(df)

encoder = LabelEncoder()
df_encoded = encoder.fit_transform(df)  # 경고메시지는 1d array로 입력하라는 것. df['class']
display(df_encoded)
print(encoder.classes_)
print(encoder.inverse_transform(df_encoded))    # 디코딩

Class
0     A
1     B
2     A
3     C
4     E
5     D
6     D
7     A
8     F

c:\Users\ALT\anaconda3\envs\bbg\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([0, 1, 0, 2, 4, 3, 3, 0, 5])

['A' 'B' 'C' 'D' 'E' 'F']
['A' 'B' 'A' 'C' 'E' 'D' 'D' 'A' 'F']


**▶ One-Hot Encoding**

In [28]:
'''
- get_dummies() 후에 concat((), axis=1) 을 사용
- OneHotEncoder는 LabelEncoder나 .values등으로 1차원 넘파이로 변환 후 2차원으로 다시 변환해야 함.
- 넘파이의 where() 나 판다스의 loc인덱서 + 부올린 인덱싱으로도 가능.
'''
df = pd.DataFrame({'Class': ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F']})
display(df)

df_encoded = pd.get_dummies(df)
pd.concat((df, df_encoded), axis=1)

Class
0     A
1     B
2     A
3     C
4     E
5     D
6     D
7     A
8     F

Class  Class_A  Class_B  Class_C  Class_D  Class_E  Class_F
0     A        1        0        0        0        0        0
1     B        0        1        0        0        0        0
2     A        1        0        0        0        0        0
3     C        0        0        1        0        0        0
4     E        0        0        0        0        1        0
5     D        0        0        0        1        0        0
6     D        0        0        0        1        0        0
7     A        1        0        0        0        0        0
8     F        0        0        0        0        0        1

In [35]:
titanic = load_dataset('titanic')
display(titanic.head(3))

titanic['요금_대중소'] = pd.cut(titanic['fare'], bins=[0, 20, 70, 300], labels=['low', 'middle', 'high'])
titanic_encoded = pd.get_dummies(titanic['요금_대중소'])
display(pd.concat((titanic, titanic_encoded), axis=1))

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  요금_대중소  low  middle  \
0      man        True  NaN  Southampton    no  False     low    1       0   
1    woman       False    C    Cherbourg   yes  False    high    0       0   
2    woman       False  NaN  Southampton   yes   True     low    1       0   
3    woman       False    C  Southampton   yes  False  middle    0       1   
4      man        True  NaN  Southampton    no   True     low    1       0   
..     ...         ...  ...          ...   ...    ...     ...  ...     ...   
886    man        True  NaN  Southampton    no   True     low    1       0   
887  woman       False    B  Southampton   yes   True  middle    0       1   
888  woman       False  NaN  Southampton    no  False  middle    0       1   
889    man        True    C    Cherbourg   yes   True  middle    0       1   
890    man        True  NaN   Queenstown    no   True     low    1       0   

     high  
0       0  
1       1  
2       0  
3       0  
4       0  
..    ...  
886     0  
887     0  
888     0  
889     0  
890     0  

[891 rows x 19 columns]

### 데이터 스케일링

**▶ StandardScaler**  
- 평균을 기준으로 얼마나 떨어져 있는지를 나타냄
- 표준화 후, 특정 범위를 벗어난 데이터를 이상치로 판별할 수도 있음

**▶ MinMaxScaler**
- 데이터군내에서 특정 개체가 가지는 위치를 파악하고 비교할 때 사용

### 데이터 축소

**▶ PCA　(Principal Component Analysis, 주성분분석)**  

In [50]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

df = pd.read_csv('samples/예제/USArrests_rownames.csv', index_col=0)
display(df.head(3))

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)

pca = PCA(4)    # n_components=4 주성분 개수를 전체 컬럼 수로.
pca_arr = pca.fit_transform(df_scaled)
print('분산 기여율: ', pca.explained_variance_ratio_)
print('누적 기여율: ', pca.explained_variance_ratio_.cumsum())      # 주성분 개수를 2개로 정함

pca = PCA(2)
pca_arr = pca.fit_transform(df_scaled)
pd.DataFrame(pca_arr, columns=['PCA1', 'PCA2']).head()

Murder  Assault  UrbanPop  Rape
Alabama    13.2      236        58  21.2
Alaska     10.0      263        48  44.5
Arizona     8.1      294        80  31.0

분산 기여율:  [0.62006039 0.24744129 0.0891408  0.04335752]
누적 기여율:  [0.62006039 0.86750168 0.95664248 1.        ]


PCA1      PCA2
0  0.985566  1.133392
1  1.950138  1.073213
2  1.763164 -0.745957
3 -0.141420  1.119797
4  2.523980 -1.542934

### 데이터 결합 및 요약

**▶ concat**
- 물리적으로 연결

**▶ merge**
- df1.merge(df2, how='inner', on=컬럼명)
- 고유한 키를 기준으로 두 데이터프레임을 병합 = 조인 (how='inner'가 디폴트. 'left', 'right', 'outer'도 가능)

**▶ groupby**

**▶ agg**

**▶ map**
- 시리즈에만 사용 가능

**▶ apply**


### 결측치와 이상치



### 텍스트 데이터와 날짜시간 데이터

# 가설 검정  
모집단에 대한 가설을 설정한 후 그 가설의 타당성 여부를 검정하는 것.
- 상관분석
- 정규성 검정
- 모평균과 모분산 검정
- 카이제곱 검정
- 비모수 검정

**▶ 상관분석**
- 데이터가 정규분포를 따를 때, 상관분석 -> 피어슨 상관계수

In [60]:
from sklearn.datasets import load_diabetes
from scipy import stats

diabetes = pd.DataFrame(load_diabetes()['data'], columns=load_diabetes()['feature_names'])
display(diabetes.head(2))

p, pvalue = stats.pearsonr(diabetes['age'], diabetes['bmi'])        # 피어슨 상관계수
print('피어슨 상관계수: ', p)
print('pvalue(유의확률): ', pvalue, pvalue < 0.05)
# 상관계수가 0.185로 두 컬럼은 서로 상관관계가 적은 것으로 나타났다. 하지만 귀무가설이 기각됐기 때문에, 상관계수는 작지만 유의하다는 것을 알수 있다.

display(diabetes[['age', 'bmi']].corr())        # 단순한 상관계수는 corr()로도 확인 가능.

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204

피어슨 상관계수:  0.18508466614655558
pvalue(유의확률):  9.076791865412659e-05 True


age       bmi
age  1.000000  0.185085
bmi  0.185085  1.000000

**▶ 정규성 검정**
- 샤피로-윌크 검정　　(R언어의 한계 때문에 이거만. scipy.stats에는 더 다양한 정규성 검정 함수가 있음. kstest, anderson, jarque_bera 등)

In [63]:
from scipy import stats

np.random.seed(2024)
data = np.random.random(10)

s, pvalue = stats.shapiro(data)
print('통계량: ', s)
print('pvalue: ', pvalue, pvalue < 0.05)    # p-value가 매우 크므로 귀무가설을 기각할 수 없기 때문에, 정규성을 만족한다.

통계량:  0.8969665765762329
pvalue:  0.20285499095916748 False


**▶ 모평균 검정**
- 표본 수에 따라 단일표본, 이표본 등으로 구분됨.
- 여기서는 단일표본 t-검정, 대응표본 t-검정, 독립표본 t-검정 이 세가지의 t-검정을 할거다.
    - 단측 검정할 때는 alternative='less', 'greater' 를 사용.

In [67]:
# t_test_1samp(데이터, 귀무가설값, alternative='two-sided')
from scipy import stats

kg = np.array([75.5, 83.9, 75.7, 56.2, 73.4, 67.7, 79.0, 50.7, 58.4, 74.1, 65.1, 77.8, 48.1, 46.3])
print(kg.mean())    # 모집단의 평균이 70이라고 할 수 있는지 단일표본 t-검정을 수행. (정규성 만족 가정)
t, pvalue = stats.ttest_1samp(kg, 70)
print('t통계량: ', t)
print('pvalue: ', pvalue, pvalue < 0.05)        # 귀무가설 채택. 모집단의 평균은 70이라고 할 수 있다.

66.56428571428572
t통계량:  -1.0289933120202257
pvalue:  0.3222484823978743 False


In [69]:
from scipy import stats

female = np.array([50.7, 58.4, 74.1, 65.1, 77.8, 48.1, 46.3])
male = np.array([75.5, 83.9, 75.7, 56.2, 73.4, 67.7, 79.0])
print('평균 차이: ', female.mean() - male.mean())       # 두 데이터의 모평균은 다르다고 할 수 있는지 대응표본 t-검정을 수행. (정규성 만족 가정)

t, pvalue = stats.ttest_rel(female, male)
print('t통계량: ', t)
print('pvalue: ', pvalue, pvalue < 0.05)        # 귀무가설 채택. 모집단의 평균은 서로 다르다고 볼 수 없다.

평균 차이:  -12.985714285714295
t통계량:  -2.0784469330649724
pvalue:  0.08291274205610197 False


In [70]:
from scipy import stats

# 바로 위의 데이터로 두 데이터가 독립이라고 가정한 후, 두 데이터에 대한 모평균이 서로 다르다고 할 수 있는 지 독립표본 t-검증을 수행. (정규성, 등분산성 만족 가정)

t, pvalue = stats.ttest_ind(female, male)
print('t통계량: ', t)
print('pvalue: ', pvalue, pvalue < 0.05)        # 귀무가설 기각. 모집단의 평균은 서로 다르다고 볼 수 있다.

t통계량:  -2.218664157777296
pvalue:  0.04655012211056963 True


**▶ 모분산 검정**
- 모분산 검정도 표본의 수에 따라 구분됨.
- 단일표본에 대한 모분산 검정, 이표본에 대한 분산비 검정, 이표본 이상에 대한 Bartlett 검정, Levene 검정

In [71]:
from scipy import stats

score = np.array([80.5, 60.2, 70, 87, 45, 91, 85])
var0 = 1100      # 귀무가설에서 설정한 모분산
sample_var = np.var(score, ddof=1)
print(sample_var)

278.1033333333333
