In [1]:
import numpy as np; import pandas as pd; p = print; import matplotlib.pyplot as plt; from sklearn.datasets import load_iris; from seaborn import load_dataset

# Python ~ Numpy ~ Pandas

**▶ range / reversed**

In [3]:
'''
range도 기본적으로 sequence형이라 iterable하게 쓸 수 있는 것이다.
    - 인덱싱과 슬라이싱 가능
'''
print(range(1, 11)[7])
print(range(1, 11)[3:7])    # range를 슬라이싱하면 range 객체로 나온다.
'''
reversed는 reversed 객체로 리턴됨.
'''
print(reversed('abcde'))
print(reversed([1, 2, 3 ,4, 5]))
print(reversed((1, 2, 3, 4, 5)))
print(reversed(range(10)))

8
range(4, 8)


**▶ ndarray**

In [28]:
'''
numpy 배열을 만들 때 dtype 인자를 사용하면 데이터 타입을 바꿀 수 있다.  ★
'''
print(arr:=np.array([3, 4, 5, 6], dtype='str'))
print(type(arr))
print(np.zeros((2, 4), dtype='float'))
print(np.full((2, 5), 9))       # 9로 채운 행렬 만들기
print(np.identity(3))           # 단위행렬
p()
arr = np.arange(1, 13).reshape(4, -1)
print(arr)
print(arr[-2, -2])
print(arr[-3:, 1:])
print(arr[1:3, :])

['3' '4' '5' '6']
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[9 9 9 9 9]
 [9 9 9 9 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
8
[[ 5  6]
 [ 8  9]
 [11 12]]
[[4 5 6]
 [7 8 9]]


In [40]:
# abs(numpy.ndarray)
arr = np.array([3, -4, -5, 6, 0])
print(np.abs(arr))
print(np.fabs(arr))     # 복소수가 아닌 경우에는 fabs로 빠르게 연산 가능하다고 함
print(np.sign(arr))     # 부호만 가져옴. 0의 부호는 0
'''넘파이 연산
     np.sqrt(arr)  np.square(arr)  np.exp(arr)  np.log(arr)  np.log10(arr)
     np.round(arr, 2)  np.ceil(arr)  np.floor(arr)'''
print(np.trunc([3.14, -4.15, -5.79, 6.88]))     # 일반적인 올림, 내림과는 다르게 소수점 파트를 삭제함.
'''형상 변환 
     arr.reshape()  arr.ravel() == arr.flatten()  arr.transpose()
   통계
     np.mean(arr)  np.min(arr)  np.max(arr)
     np.var(arr, ddof=None)  np.std(arr, ddof=None)     ← ddof = 자유도. 표본 통계량을 구할 때는 ddof=1을 줘야 함. ★
     np.argmin(arr)  np.argmax(arr)                    ★
'''; p()

[3 4 5 6 0]
[3. 4. 5. 6. 0.]
[ 1 -1 -1  1  0]
[ 3. -4. -5.  6.]



**▶ DataFrame**

In [53]:
'''
    pd.DataFrame(object, index, columns)
'''
df = pd.DataFrame({
    'Name': ['Olivia', 'Lucas', 'Sophia', 'Zoe', 'Aca', 'Elliot'],
    'Sex': ['F', 'M', 'F', 'F', 'F', 'M'],
    'Age': [22, 32, 27, 24, 38, 19]
}, index=list('abcdef'))
display(df)
print(df.iloc[3, 0])
print(df.loc['d', 'Age'])
print(df.iloc[2:5])
print(df.loc['c':'e'])      # loc는 마지막 슬라이싱 행이 포함됨. 지져스
print(df['Name']['c'], df['Name'][2])       # 인덱서 없이 인덱싱할 때는 열 → 행 순서. 걍 loc나 iloc 쓰자.

Name Sex  Age
a  Olivia   F   22
b   Lucas   M   32
c  Sophia   F   27
d     Zoe   F   24
e     Aca   F   38
f  Elliot   M   19

Zoe
24
     Name Sex  Age
c  Sophia   F   27
d     Zoe   F   24
e     Aca   F   38
     Name Sex  Age
c  Sophia   F   27
d     Zoe   F   24
e     Aca   F   38
Sophia Sophia


In [68]:
'''데이터 프레임의 통계
        df.describe()  df.count()  df.mean()  df.min()  df.max()
        df.var(ddof=1)  df.std(ddof=1)      ← 넘파이와는 다르게 ddof=1이 디폴트 ★
        df.median()  df.quantile(q=0.5)  df.mode()     ★

   입출력
        pd.read_csv(path, sep=',', encoding=None)
        pd.to_csv(path, index=True)

   정렬
        df.sort_values(by, ascending=True, axis=0)
        df.sort_index(axis=0, ascending=True, level=None)       ← axis=1이면 열 인덱스(특성 순서)을 정렬함

   순위
        df.rank(axis=0, method='average', ascending=True)

   컬럼 추가, 삭제, 구간화
        df['컬럼명'] = 추가할 컬럼
        df.insert(loc, column, value)
        df.drop(labels, axis=0)
        pd.cut(x, bins, labels=None, right=True)        ← 구간화(비닝, binning)
        pd.qcut(x, q, labels=None, right=True)          ← 분위수 기반의 구간화
'''
iris = pd.DataFrame(load_iris()['data'], columns=load_iris()['feature_names'])
iris['cut'] = pd.cut(iris['sepal length (cm)'], bins=5)
print(iris['cut'].unique())

[(5.02, 5.74], (4.296, 5.02], (5.74, 6.46], (6.46, 7.18], (7.18, 7.9]]
Categories (5, interval[float64, right]): [(4.296, 5.02] < (5.02, 5.74] < (5.74, 6.46] < (6.46, 7.18] < (7.18, 7.9]]


# 데이터 인코딩

**▶ Label Encoding**

In [10]:
'''
- 단순하게 문자열 값을 숫자형 카테고리 값으로 일대일로 변환.
- 숫자가 대소의 의미를 가지게 되므로, 가급적 트리 계열과 같은 특정 머신러닝 알고리즘에서만 사용해야 한다.
- 넘파이의 select()나 판다스의 map()으로도 같은 기능 가능
'''
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({'Class': ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F']})
display(df)

encoder = LabelEncoder()
df_encoded = encoder.fit_transform(df)  # 경고메시지는 1d array로 입력하라는 것. df['class']
display(df_encoded)
print(encoder.classes_)
print(encoder.inverse_transform(df_encoded))    # 디코딩

Class
0     A
1     B
2     A
3     C
4     E
5     D
6     D
7     A
8     F

c:\Users\ALT\anaconda3\envs\bbg\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([0, 1, 0, 2, 4, 3, 3, 0, 5])

['A' 'B' 'C' 'D' 'E' 'F']
['A' 'B' 'A' 'C' 'E' 'D' 'D' 'A' 'F']


**▶ One-Hot Encoding**

In [28]:
'''
- get_dummies() 후에 concat((), axis=1) 을 사용
- OneHotEncoder는 LabelEncoder나 .values등으로 1차원 넘파이로 변환 후 2차원으로 다시 변환해야 함.
- 넘파이의 where() 나 판다스의 loc인덱서 + 부올린 인덱싱으로도 가능.
'''
df = pd.DataFrame({'Class': ['A', 'B', 'A', 'C', 'E', 'D', 'D', 'A', 'F']})
display(df)

df_encoded = pd.get_dummies(df)
pd.concat((df, df_encoded), axis=1)

Class
0     A
1     B
2     A
3     C
4     E
5     D
6     D
7     A
8     F

Class  Class_A  Class_B  Class_C  Class_D  Class_E  Class_F
0     A        1        0        0        0        0        0
1     B        0        1        0        0        0        0
2     A        1        0        0        0        0        0
3     C        0        0        1        0        0        0
4     E        0        0        0        0        1        0
5     D        0        0        0        1        0        0
6     D        0        0        0        1        0        0
7     A        1        0        0        0        0        0
8     F        0        0        0        0        0        1

In [35]:
titanic = load_dataset('titanic')
display(titanic.head(3))

titanic['요금_대중소'] = pd.cut(titanic['fare'], bins=[0, 20, 70, 300], labels=['low', 'middle', 'high'])
titanic_encoded = pd.get_dummies(titanic['요금_대중소'])
display(pd.concat((titanic, titanic_encoded), axis=1))

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  요금_대중소  low  middle  \
0      man        True  NaN  Southampton    no  False     low    1       0   
1    woman       False    C    Cherbourg   yes  False    high    0       0   
2    woman       False  NaN  Southampton   yes   True     low    1       0   
3    woman       False    C  Southampton   yes  False  middle    0       1   
4      man        True  NaN  Southampton    no   True     low    1       0   
..     ...         ...  ...          ...   ...    ...     ...  ...     ...   
886    man        True  NaN  Southampton    no   True     low    1       0   
887  woman       False    B  Southampton   yes   True  middle    0       1   
888  woman       False  NaN  Southampton    no  False  middle    0       1   
889    man        True    C    Cherbourg   yes   True  middle    0       1   
890    man        True  NaN   Queenstown    no   True     low    1       0   

     high  
0       0  
1       1  
2       0  
3       0  
4       0  
..    ...  
886     0  
887     0  
888     0  
889     0  
890     0  

[891 rows x 19 columns]

### 데이터 스케일링

**▶ StandardScaler**  
- 평균을 기준으로 얼마나 떨어져 있는지를 나타냄
- 표준화 후, 특정 범위를 벗어난 데이터를 이상치로 판별할 수도 있음

**▶ MinMaxScaler**
- 데이터군내에서 특정 개체가 가지는 위치를 파악하고 비교할 때 사용

### 데이터 축소

**▶ PCA　(Principal Component Analysis, 주성분분석)**  

In [50]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

df = pd.read_csv('samples/예제/USArrests_rownames.csv', index_col=0)
display(df.head(3))

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)

pca = PCA(4)    # n_components=4 주성분 개수를 전체 컬럼 수로.
pca_arr = pca.fit_transform(df_scaled)
print('분산 기여율: ', pca.explained_variance_ratio_)
print('누적 기여율: ', pca.explained_variance_ratio_.cumsum())      # 주성분 개수를 2개로 정함

pca = PCA(2)
pca_arr = pca.fit_transform(df_scaled)
pd.DataFrame(pca_arr, columns=['PCA1', 'PCA2']).head()

Murder  Assault  UrbanPop  Rape
Alabama    13.2      236        58  21.2
Alaska     10.0      263        48  44.5
Arizona     8.1      294        80  31.0

분산 기여율:  [0.62006039 0.24744129 0.0891408  0.04335752]
누적 기여율:  [0.62006039 0.86750168 0.95664248 1.        ]


PCA1      PCA2
0  0.985566  1.133392
1  1.950138  1.073213
2  1.763164 -0.745957
3 -0.141420  1.119797
4  2.523980 -1.542934

### 데이터 결합 및 요약

**▶ concat**
- 물리적으로 연결

**▶ merge**
- df1.merge(df2, how='inner', on=컬럼명)
- 고유한 키를 기준으로 두 데이터프레임을 병합 = 조인 (how='inner'가 디폴트. 'left', 'right', 'outer'도 가능)

**▶ groupby**

**▶ agg**

**▶ map**
- 시리즈에만 사용 가능

**▶ apply**


### 결측치와 이상치



### 텍스트 데이터와 날짜시간 데이터

# 가설 검정  
모집단에 대한 가설을 설정한 후 그 가설의 타당성 여부를 검정하는 것.
- 상관분석
- 정규성 검정
- 모평균과 모분산 검정
- 카이제곱 검정
- 비모수 검정

### **▼ 상관분석**
- 데이터가 정규분포를 따를 때, 상관분석 -> 피어슨 상관계수

In [60]:
from sklearn.datasets import load_diabetes
from scipy import stats

diabetes = pd.DataFrame(load_diabetes()['data'], columns=load_diabetes()['feature_names'])
display(diabetes.head(2))

p, pvalue = stats.pearsonr(diabetes['age'], diabetes['bmi'])        # 피어슨 상관계수
print('피어슨 상관계수: ', p)
print('pvalue(유의확률): ', pvalue, pvalue < 0.05)
# 상관계수가 0.185로 두 컬럼은 서로 상관관계가 적은 것으로 나타났다. 하지만 귀무가설이 기각됐기 때문에, 상관계수는 작지만 유의하다는 것을 알수 있다.

display(diabetes[['age', 'bmi']].corr())        # 단순한 상관계수는 corr()로도 확인 가능.

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204

피어슨 상관계수:  0.18508466614655558
pvalue(유의확률):  9.076791865412659e-05 True


age       bmi
age  1.000000  0.185085
bmi  0.185085  1.000000

### **▼ 정규성 검정**
- 샤피로-윌크 검정　　(R언어의 한계 때문에 이거만. scipy.stats에는 더 다양한 정규성 검정 함수가 있음. kstest, anderson, jarque_bera 등)

In [63]:
from scipy import stats

np.random.seed(2024)
data = np.random.random(10)

s, pvalue = stats.shapiro(data)
print('통계량: ', s)
print('pvalue: ', pvalue, pvalue < 0.05)    # p-value가 매우 크므로 귀무가설을 기각할 수 없기 때문에, 정규성을 만족한다.

통계량:  0.8969665765762329
pvalue:  0.20285499095916748 False


### **▼ 모평균 검정**
- 표본 수에 따라 단일표본, 이표본 등으로 구분됨.
- 여기서는 단일표본 t-검정, 대응표본 t-검정, 독립표본 t-검정 이 세가지의 t-검정을 할거다.
    - 단측 검정할 때는 alternative='less', 'greater' 를 사용.

In [67]:
# t_test_1samp(데이터, 귀무가설값, alternative='two-sided')
from scipy import stats

kg = np.array([75.5, 83.9, 75.7, 56.2, 73.4, 67.7, 79.0, 50.7, 58.4, 74.1, 65.1, 77.8, 48.1, 46.3])
print(kg.mean())    # 모집단의 평균이 70이라고 할 수 있는지 단일표본 t-검정을 수행. (정규성 만족 가정)
t, pvalue = stats.ttest_1samp(kg, 70)
print('t통계량: ', t)
print('pvalue: ', pvalue, pvalue < 0.05)        # 귀무가설 채택. 모집단의 평균은 70이라고 할 수 있다.

66.56428571428572
t통계량:  -1.0289933120202257
pvalue:  0.3222484823978743 False


In [69]:
from scipy import stats

female = np.array([50.7, 58.4, 74.1, 65.1, 77.8, 48.1, 46.3])
male = np.array([75.5, 83.9, 75.7, 56.2, 73.4, 67.7, 79.0])
print('평균 차이: ', female.mean() - male.mean())       # 두 데이터의 모평균은 다르다고 할 수 있는지 대응표본 t-검정을 수행. (정규성 만족 가정)

t, pvalue = stats.ttest_rel(female, male)
print('t통계량: ', t)
print('pvalue: ', pvalue, pvalue < 0.05)        # 귀무가설 채택. 모집단의 평균은 서로 다르다고 볼 수 없다.

평균 차이:  -12.985714285714295
t통계량:  -2.0784469330649724
pvalue:  0.08291274205610197 False


In [70]:
from scipy import stats

# 바로 위의 데이터로 두 데이터가 독립이라고 가정한 후, 두 데이터에 대한 모평균이 서로 다르다고 할 수 있는 지 독립표본 t-검증을 수행. (정규성, 등분산성 만족 가정)

t, pvalue = stats.ttest_ind(female, male)
print('t통계량: ', t)
print('pvalue: ', pvalue, pvalue < 0.05)        # 귀무가설 기각. 모집단의 평균은 서로 다르다고 볼 수 있다.

t통계량:  -2.218664157777296
pvalue:  0.04655012211056963 True


### **▼ 모분산 검정**
- 모분산 검정도 표본의 수에 따라 구분됨.
- 단일표본에 대한 모분산 검정, 이표본에 대한 분산비 검정, 이표본 이상에 대한 Bartlett 검정과 Levene 검정

In [78]:
# 단일 표본에 대한 모분산 검정을 바로 수행하는 함수가 없어서, chi2으로 cdf해서 유의확률을 구해야 한다.
from scipy import stats

score = np.array([80.5, 60.2, 70, 87, 45, 91, 85])
var0 = 1100      # 귀무가설에서 설정한 모분산
sample_var = np.var(score, ddof=1)          # 표본 분산
print('표본 분산: ', sample_var)

stat = (len(score)-1) * sample_var / var0   # 검정 통계량
print('검정통계량: ', stat)
print(stats.chi2.cdf(stat, len(score)-1))   # 카이분포를 통해 직접 유의확률 계산. 좌측 검정이므로 Pr[chi2(자유도) < 검정통계량]으로 계산
print('> 검정 결과 p-value가 0.0416이므로 유의수준 5%에서 귀무가설을 기각. 모분산은 1100보다 작다고 할 수 있다.')
print(1 - stats.chi2.cdf(stat, len(score)-1))   # 우측 검정일 경우, Pr[chi2(자유도) > 검정통계량]으로 계산
print(2 * stats.chi2.cdf(stat, len(score)-1))   # 양측 검정일 경우, 2 * 좌측검정의 유의확률 또는 2* 우측검정의 유의확률로 계산

표본 분산:  278.1033333333333
검정통계량:  1.5169272727272727
0.041637780038918736
> 검정 결과 p-value가 0.0416이므로 유의수준 5%에서 귀무가설을 기각. 모분산은 1100보다 작다고 할 수 있다.
0.9583622199610813
0.08327556007783747


In [80]:
# 분산비 검정은 일반적으로 이표본에 대한 등분산 검정을 의미. 이 또한 바로 수행하는 함수가 없어서, f분포로 cdf해서 유의확률을 구해야 한다.
# 대립가설: a 모분산 < b 모분산으로 가정. 정규성 만족 가정.
from scipy import stats

a = np.array([70, 80, 75, 65, 100, 98])
b = np.array([20, 100, 50, 94, 28, 80, 95, 30])

var_a = np.var(a, ddof=1)       # 표본 분산
var_b = np.var(b, ddof=1)

stat = var_a / var_b
print('검정통계량: ', stat)         # 검정통계량 = a의 분산 / b의 분산 (가설: a 모분산 < b 모분산)
print(stats.f.cdf(stat, len(a)-1, len(b)-1))        # F분포로 직접 유의확률 계산. 좌측검정을 함.
print('> 유의확률이 0.0415로 유의수준 5%에서 귀무가설을 기각. a 모분산은 b 모분산보다 작다고 할 수 있다.')
print(1 - stats.f.cdf(stat, len(a)-1, len(b)-1))    # 우측 검정
print(2 * stats.f.cdf(stat, len(a)-1, len(b)-1))    # 양측 검정

검정통계량:  0.18681014154026346
0.04153943037562959
> 유의확률이 0.0415로 유의수준 5%에서 귀무가설을 기각. a 모분산은 b 모분산보다 작다고 할 수 있다.
0.9584605696243704
0.08307886075125918


In [86]:
# Bartlett 검정
# 이표본 이상에 대한 등분산 검정 방법 중 하나로 정규성을 충족해야함.
from scipy import stats

a = np.array([70, 80, 75, 65, 100, 98])
b = np.array([20, 100, 50, 94, 28, 80])
c = np.array([90, 97, 95, 94, 99, 100])

print(stats.bartlett(a, b, c))  # 유의확률이 0.05보다 작으므로, 그룹 간의 분산에 유의미한 차이가 있다고 볼 수 있다.

BartlettResult(statistic=15.6702722148674, pvalue=0.00039558846873743075)


In [87]:
# Levene 검정
# 이표본 이상에 대한 등분산 검정 방법 중 하나로 정규성을 충족하지 않는 데이터에 사용.
from scipy import stats

print(stats.levene(a, b, c))    # 유의확률이 0.05보다 작으므로, 그룹 간의 분산에 유의미한 차이가 있다고 볼 수 있다.

LeveneResult(statistic=14.365736704446384, pvalue=0.00032713621045500125)


**▶ 분산 분석 ANOVA**
- 분산 분석(ANOVA)는 두 집단 이상의 모평균을 검정하는 방법.
- 여기서는 일원배치 분산분석과 이원배치 분산분석만 다룰거임.

In [93]:
# 일원배치 분산분석
# A~C 세 학교에서 각각 1000명씩 층화 추출한 데이터를 활용해서 세 학교 간의 기말고사 성적의 평균이 서로 차이가 있는 지 검정. (성별, 학년의 비율은 세 학교가 동일, 정규성, 등분산성 등 만족 가정)
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

df = pd.read_csv('samples/예제/school_score.csv')
print(df.shape)
display(df.head(2))

one_way = ols('Final ~ C(School)', data=df).fit()
display(anova_lm(one_way))
# C(School)의 PR(>F)값이 매우 작으므로, 유의수준 5%에서 귀무가설을 기각. 세 학교의 기말고사 성적의 평균은 차이가 있다고 할 수 있다.

(3000, 5)


id School Sex  Grade  Final
0   1      A   M      1   44.4
1   2      A   M      2   47.7

df         sum_sq        mean_sq            F  PR(>F)
C(School)     2.0  996939.237147  498469.618573  5722.221007     0.0
Residual   2997.0  261072.308290      87.111214          NaN     NaN

In [94]:
# 사후검정 - Tukey의 HSD 검정
# 바로 위에서 세 학교의 평균에 차이가 있음을 알았지만, 세 학교가 모두 다른지, A와 B만 다른지, A와 C가 다른지는 알 수가 없다.
# 이를알기 위해서는 사후검정을 해야 한다.

from statsmodels.stats.multicomp import pairwise_tukeyhsd

print(pairwise_tukeyhsd(df['Final'], df['School'], 0.05))   # endog=df['Final'], groups=df['School'], alpha=0.05
# A와 B, A와 C 사이에는 평균에 유의미한 차이가 있다고 할 수 있고, B와 C는 유의미한 차이가 없다고 할 수 있다.
# 신뢰구간에 0을 포함하는지 아니면 reject 결과로 알 수 있다.

Multiple Comparison of Means - Tukey HSD, FWER=0.05 
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     A      B  38.8464   -0.0 37.8677 39.8251   True
     A      C  38.4922   -0.0 37.5135 39.4709   True
     B      C  -0.3542 0.6728 -1.3329  0.6245  False
----------------------------------------------------


In [100]:
# 이원배치 분산분석
# 이원배치 분산분석은 일원배치 분산분석과 유하하지만, formula 입력 방식에 차이가 있다.
# 교호작용이 있는 경우: '반응변수 ~ C(그룹1) + C(그룹2) + C(그룹1):C(그룹2)'
# 교호작용이 없는 경우: '반응변수 ~ C(그룹1) + C(그룹2)'

from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

df = pd.read_csv('samples/예제/school_score.csv')

two_way = ols('Final ~ C(School) + C(Grade) + C(School):C(Grade)', df).fit()
display(anova_lm(two_way))
print('> 이원배치 분산분석에서는 상호작용항의 유의성을 먼저 고려한다. 0.742912로 p-value가 매우 크므로, 상호작용 효과가 통계적으로 유의하지 않은 것을 알 수있다.')
print('> 교호작용이 유의하지 않으므로, 이를 고려하지 않고 다시 분산분석을 수행한다. \n')
two_way = ols('Final ~ C(School) + C(Grade)', df).fit()
display(anova_lm(two_way))
print('> 학교의 p-value는 매우 작으므로, 학교간의 평균차이는 있다고 볼 수 있고, 학년의 p-value는 0.05를 넘으므로, 학년간의 차이는 유의미하지 않다고 볼 수 있다.')

df         sum_sq        mean_sq            F  \
C(School)              2.0  996939.237147  498469.618573  5721.620556   
C(Grade)               2.0     324.472829     162.236415     1.862210   
C(School):C(Grade)     4.0     170.851257      42.712814     0.490274   
Residual            2991.0  260576.984204      87.120356          NaN   

                      PR(>F)  
C(School)           0.000000  
C(Grade)            0.155509  
C(School):C(Grade)  0.742912  
Residual                 NaN

> 이원배치 분산분석에서는 상호작용항의 유의성을 먼저 고려한다. 0.742912로 p-value가 매우 크므로, 상호작용 효과가 통계적으로 유의하지 않은 것을 알 수있다.
> 교호작용이 유의하지 않으므로, 이를 고려하지 않고 다시 분산분석을 수행한다. 



df         sum_sq        mean_sq            F    PR(>F)
C(School)     2.0  996939.237147  498469.618573  5725.518315  0.000000
C(Grade)      2.0     324.472829     162.236415     1.863479  0.155312
Residual   2995.0  260747.835461      87.061047          NaN       NaN

> 학교의 p-value는 매우 작으므로, 학교간의 평균차이는 있다고 볼 수 있고, 학년의 p-value는 0.05를 넘으므로, 학년간의 차이는 유의미하지 않다고 볼 수 있다.


### **▼ 카이제곱 검정**
- 주로 범주형 자료 분석에 사용.
- 적합성 검정, 동질성 검정, 독립성 검정

**▶ 적합성 검정** 

In [104]:
# A 회사에서 출시되는 제품 공정 결과의 예를 보고, 색상과 관계없이 동일한 비율로 제품을 생산하는 지 적합성 검정을 수행하자

from scipy import stats

color = ['Black','Gold','Purple','Red', 'White']    # 색상(분석엔 필요 X)
counts = [423, 304, 274, 205, 294]                  # 수량
expected = 300                          # 기대도수(동일한 비율 = 1500/5)

print(stats.chisquare(counts, expected))        # f_obs=counts, f_exp=expected
print('> p-value가 0.05보다 작으므로 귀무가설을 기각. 색상별로 동일한 비율로 생산한다고 볼 수 없다.')

Power_divergenceResult(statistic=82.94, pvalue=4.14849046718008e-17)
> p-value가 0.05보다 작으므로 귀무가설을 기각. 색상별로 동일한 비율로 생산한다고 볼 수 없다.


**▶ 동질성 검정** 

In [111]:
# A 회사의 성별에 따른 제품 선호도조사의 예를 보고, 성별 간 선호도의 차이 검증을 위한 동질성 검정을 수행하자

from scipy import stats

cross = pd.DataFrame({"Good" : [400 , 350],"Bad" : [350, 800]}, index=['남성', '여성'])
display(cross)

print(stats.chi2_contingency(cross))
chi, pvalue, df, expected = stats.chi2_contingency(cross)   # 카이제곱통계량, 유의확률, 자유도, 기대빈도
print('> p-value가 0.05보다 작으므로 귀무가설 기각. 성별 간 선호도의 차이가 있다고 볼 수 있다.')

Good  Bad
남성   400  350
여성   350  800

(98.66917336693975, 2.984113573360021e-23, 1, array([[296.05263158, 453.94736842],
       [453.94736842, 696.05263158]]))
> p-value가 0.05보다 작으므로 귀무가설 기각. 성별 간 선호도의 차이가 있다고 볼 수 있다.


**▶ 독립성 검정** 

In [115]:
# A 회사의 출시된 제품의 한 달 간 판매량의 예이다. 이를 통해 성별과 색상이 서로 관련이 있는 지 알아보기 위해 독립성 검정을 수행하자.
from scipy import stats

cross = pd.DataFrame({'Black' : [1620, 2380],'Gold' : [385, 615],'Purple' : [778, 1230],'Red' : [394, 610],'White' : [800, 180]}, index=['남성', '여성'])
display(cross)

chi, pvalue, df, expected = stats.chi2_contingency(cross)
print('카이제곱통계량: ', chi)
print('pvalue: ', pvalue)
print('> p-vale가 0.05보다 작으므로 귀무가설을 기각. 성별과 색상은 독립성이 없다 즉, 종속적이고 관련이 있다.')
print('자유도: ', df, '\n 기대빈도: \n', expected)

Black  Gold  Purple  Red  White
남성   1620   385     778  394    800
여성   2380   615    1230  610    180

카이제곱통계량:  626.2830361414021
pvalue:  3.1731601033660286e-134
자유도:  4 
 기대빈도: 
 [[1769.12811388  442.28202847  888.10231317  444.05115658  433.4363879 ]
 [2230.87188612  557.71797153 1119.89768683  559.94884342  546.5636121 ]]


**● 교차표 만드는 법**   
pd.crosstab(index, columns)

In [118]:
display(titanic.head())
pd.crosstab(titanic['sex'], titanic['embark_town'])

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  요금_대중소  
0    man        True  NaN  Southampton    no  False     low  
1  woman       False    C    Cherbourg   yes  False    high  
2  woman       False  NaN  Southampton   yes   True     low  
3  woman       False    C  Southampton   yes  False  middle  
4    man        True  NaN  Southampton    no   True     low

embark_town  Cherbourg  Queenstown  Southampton
sex                                            
female              73          36          203
male                95          41          441

### **▼ 비모수 검정**
- 모수적 검정은 가설 검정 시 분포를 가정하기 때문에, 실제 데이터가 가정한 분포와 이질적일수록 잘못된 결론을 내릴 가능성이 높다.
- 실제로는 정규성 검정을 선행하여 정규성을 만족하면 모수적 검정, 정규성을 만족하지 않으면 비모수적 검정을 해야 한다.

**▶ 스피어만 상관계수** 

In [120]:
from sklearn.datasets import load_diabetes
from scipy import stats

diabetes = pd.DataFrame(load_diabetes()['data'], columns=load_diabetes()['feature_names'])
display(diabetes.head(2))

print(stats.spearmanr(diabetes['sex'], diabetes['bmi']))
print('> 상관계수 0.098로 서로 상관관계가 적다고 볼 수 있다. 다만, p-value는 0.05보다 낮으므로 귀무가설을 기각, 상관계수는 작지만 유의하다는 것을 확인할 수 있다.')

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204

SpearmanrResult(correlation=0.09807947297621517, pvalue=0.03929011358104615)
> 상관계수 0.098로 서로 상관관계가 적다고 볼 수 있다. 다만, p-value는 0.05보다 낮으므로 귀무가설을 기각, 상관계수는 작지만 유의하다는 것을 확인할 수 있다.


**▶ 켄달의 타우 검정** 

In [123]:
# 두 개의 등수 데이터를 임의로 생성하고 두 순위 간 상관관계가 있는지 검정하자.

from scipy import stats

x = np.array([5, 4, 3, 6, 1, 2])
y = np.array([1, 5, 2, 2, 2, 6])

print(stats.kendalltau(x, y))
print('> 상관계수가 -0.298로 순위 간 상관관계가 거의 없는 것으로 확인된다.')    # 스피어만 상관계수 검정은 켄탈 타우 검정과 마찬가지로 순위 데이터에 대해서도 검정을 할 수 있다!

KendalltauResult(correlation=-0.29814239699997197, pvalue=0.4205962375999267)
> 상관계수가 -0.298로 순위 간 상관관계가 거의 없는 것으로 확인된다.


**▶ 윌콕슨의 부호순위 검정** 

In [130]:
from scipy import stats

# 단일표본 t-검정 대신 일표본 부호순위 검정
kg = np.array([75.5, 83.9, 75.7, 56.2, 73.4, 67.7, 79.0, 50.7, 58.4, 74.1, 65.1, 77.8, 48.1, 46.3])

print(stats.wilcoxon(kg - 70))
print('> 귀무가설 채택. 모집단의 중위수는 70과 같다고 할 수 있다.')

 # 대응표본 t-검정 대신 이표본 부호순위 검정
female = np.array([50.7, 58.4, 74.1, 65.1, 77.8, 48.1, 46.3])      
male = np.array([75.5, 83.9, 75.7, 56.2, 73.4, 67.7, 79.0])

print(stats.wilcoxon(female, male))
print('> 귀무가설 채택. 둘의 중앙값에 유의한 차이가 없다.')

WilcoxonResult(statistic=42.0, pvalue=0.5416259765625)
> 귀무가설 채택. 모집단의 중위수는 70과 같다고 할 수 있다.
WilcoxonResult(statistic=5.0, pvalue=0.15625)
> 귀무가설 채택. 둘의 중앙값에 유의한 차이가 없다.


**▶ 윌콕슨의 순위합 검정** 

In [129]:
# 독립표본 t-검정 대신 순위합 검정
from scipy import stats

print(stats.ranksums(female, male))
print('> 귀무가설 채택. 두 표본의 중앙값에 유의한 차이가 없다.')

RanksumsResult(statistic=-1.8527420384998257, pvalue=0.06391934147515746)
> 귀무가설 채택. 두 표본의 중앙값에 유의한 차이가 없다.


**▶ 만-위트니 U 검정** 

In [132]:
# 독립표본 t-검정 대신 만-위트니 U 검정
from scipy import stats

print(stats.mannwhitneyu(female, male))
print('> 귀무가설 채택. 두 표본의 중앙값에 유의한 차이가 없다.')

MannwhitneyuResult(statistic=10.0, pvalue=0.07284382284382285)
> 귀무가설 채택. 두 표본의 중앙값에 유의한 차이가 없다.


**▶ 크루스칼-왈리스 H 검정** 

In [143]:
# 일원배치 분산분석 대신
from scipy import stats

df = pd.read_csv('samples/예제/school_score.csv')
display(df.head(2))

final_A = df.loc[df['School'] == 'A']['Final'].values
final_B = df.loc[df['School'] == 'B']['Final'].values
final_C = df.loc[df['School'] == 'C']['Final'].values
print(stats.kruskal(final_A, final_B, final_C))
print('> 귀무가설 기각. 학교 간 기말고사 성적에는 유의미한 차이가 있다.')

id School Sex  Grade  Final
0   1      A   M      1   44.4
1   2      A   M      2   47.7

KruskalResult(statistic=1978.1734792103248, pvalue=0.0)
> 귀무가설 기각. 학교 간 기말고사 성적에는 유의미한 차이가 있다.


# 통계모형 - 선형 회귀모형

# 머신러닝 - 지도학습

### **▼ 데이터 분할**

**▶ 홀드아웃** 

In [7]:
from sklearn.model_selection import train_test_split

train_X, val_X, train_Y, val_Y = train_test_split(X, Y, train_size=0.75, shuffle=True, stratify=None, random_state=None)
# stratify=Y 은 Y를 기준으로 층화추출하는 것. 목표 레이블 비율에 맞게 데이터를 분할하고자 할 때 사용.

**▶ K-Fold** 

In [10]:
from sklearn.model_selection import KFold

kfold = KFold(5)    # n_splits=5, shuffle=False
kfold.split(X, Y)

from sklearn.model_selection import StratifiedKFold     # 층화추출 K-Fold

skfold = StratifiedKFold(5)     # n_splits=5, shuffle=False
skfold.split(X, Y)

### **▼ 성과 분석**